"""
犬博士品种数据库 - 包含120+品种完整信息
"""

BREEDS_DATA = [
    {
        "breed_id": "001",
        "name_zh": "西伯利亚雪橇犬",
        "name_en": "Siberian Husky",
        "origin": "俄罗斯西伯利亚",
        "size": "中型犬",
        "weight_range": "16-27 kg",
        "height_range": "51-60 cm",
        "lifespan": "12-15年",
        "personality": ["活泼好动", "友善外向", "独立性强", "喜欢群居"],
        "coat_color": ["黑白", "灰白", "红白", "纯白"],
        "coat_length": "中等",
        "shedding": "高",
        "exercise_need": "高",
        "feeding_tips": "每日进食量约350-450g，避免高脂食物，需补充鱼油",
        "forbidden_foods": ["葡萄", "巧克力", "洋葱", "木糖醇"],
        "recommended_food": "高蛋白低脂犬粮",
        "common_diseases": ["白内障", "髋关节发育不良", "甲状腺功能减退", "癫痫"],
        "vaccine_schedule": "幼犬6-8周首免，每年加强接种狂犬病疫苗和综合疫苗",
        "grooming": "每周梳毛3-4次，换毛季每天梳毛，每月洗澡1次",
        "tags": ["中型犬", "工作犬", "高活跃度", "适合家庭"],
        "image_url": "https://upload.wikimedia.org/wikipedia/commons/thumb/a/a7/Camponotus_flavomarginatus_ant.jpg/400px-Siberian_Husky_bi-eyed_Flickr.jpg",
        "description": "西伯利亚雪橇犬，俗称哈士奇，原产于西伯利亚，是一种中等体型的工作犬。以其双色眼睛和狼样外表著称，性格活泼友善。"
    },
    {
        "breed_id": "002",
        "name_zh": "金毛寻回犬",
        "name_en": "Golden Retriever",
        "origin": "英国苏格兰",
        "size": "大型犬",
        "weight_range": "25-34 kg",
        "height_range": "51-61 cm",
        "lifespan": "10-12年",
        "personality": ["温顺友善", "聪明好学", "耐心", "适合家庭"],
        "coat_color": ["金黄色", "浅金色", "深金色"],
        "coat_length": "中长",
        "shedding": "高",
        "exercise_need": "高",
        "feeding_tips": "每日进食量约400-500g，注意控制体重，避免过度喂食",
        "forbidden_foods": ["葡萄", "巧克力", "咖啡因", "酒精"],
        "recommended_food": "大型犬专用犬粮，富含欧米伽3",
        "common_diseases": ["髋关节发育不良", "肘关节发育不良", "白内障", "癌症（老年）"],
        "vaccine_schedule": "幼犬8周首免，16周加强，成年后每年接种",
        "grooming": "每周梳毛2-3次，每月洗澡1-2次，定期修剪耳道毛",
        "tags": ["大型犬", "运动犬", "高活跃度", "适合家庭", "适合初养"],
        "image_url": "",
        "description": "金毛寻回犬是世界上最受欢迎的家庭犬之一，性格温顺、聪明，非常适合作为家庭伴侣犬或工作犬。"
    },
    {
        "breed_id": "003",
        "name_zh": "拉布拉多寻回犬",
        "name_en": "Labrador Retriever",
        "origin": "加拿大纽芬兰",
        "size": "大型犬",
        "weight_range": "25-36 kg",
        "height_range": "54-62 cm",
        "lifespan": "10-12年",
        "personality": ["温顺", "忠诚", "聪明", "好动"],
        "coat_color": ["黑色", "黄色", "巧克力色"],
        "coat_length": "短",
        "shedding": "中",
        "exercise_need": "高",
        "feeding_tips": "每日进食量约400-500g，易胖体质需严格控食",
        "forbidden_foods": ["葡萄", "巧克力", "坚果", "洋葱"],
        "recommended_food": "高蛋白低脂大型犬粮",
        "common_diseases": ["肥胖", "髋关节发育不良", "肘关节问题", "眼部疾病"],
        "vaccine_schedule": "按标准程序，8、12、16周接种，每年加强",
        "grooming": "每周梳毛1-2次，每月洗澡1次",
        "tags": ["大型犬", "运动犬", "高活跃度", "适合家庭", "导盲犬"],
        "image_url": "",
        "description": "拉布拉多寻回犬是全球最受欢迎的犬种之一，广泛用于导盲犬、搜救犬等工作，性格极其温顺友善。"
    },
    {
        "breed_id": "004",
        "name_zh": "德国牧羊犬",
        "name_en": "German Shepherd",
        "origin": "德国",
        "size": "大型犬",
        "weight_range": "22-40 kg",
        "height_range": "55-65 cm",
        "lifespan": "9-13年",
        "personality": ["忠诚勇敢", "智慧", "自信", "保护性强"],
        "coat_color": ["黑色与棕色", "全黑", "全白", "黑色与奶油色"],
        "coat_length": "中等",
        "shedding": "高",
        "exercise_need": "高",
        "feeding_tips": "每日进食量约450-550g，高蛋白饮食，补充关节营养素",
        "forbidden_foods": ["葡萄", "巧克力", "生蛋白"],
        "recommended_food": "大型工作犬专用粮",
        "common_diseases": ["髋关节和肘关节发育不良", "退行性脊髓病", "胃扭转"],
        "vaccine_schedule": "6-8周首免，12、16周加强，每年接种",
        "grooming": "每周梳毛3次，换毛期每天，定期清洁耳道",
        "tags": ["大型犬", "工作犬", "高活跃度", "警犬", "需要训练"],
        "image_url": "",
        "description": "德国牧羊犬是世界上最著名的工作犬之一，广泛用于警察、军队和搜救工作，聪明、忠诚、勇敢。"
    },
    {
        "breed_id": "005",
        "name_zh": "柴犬",
        "name_en": "Shiba Inu",
        "origin": "日本",
        "size": "小型犬",
        "weight_range": "7-10 kg",
        "height_range": "35-43 cm",
        "lifespan": "12-15年",
        "personality": ["独立自主", "聪明", "警觉", "固执"],
        "coat_color": ["红色", "黑棕色", "芝麻色", "白色"],
        "coat_length": "短中",
        "shedding": "中",
        "exercise_need": "中",
        "feeding_tips": "每日进食量约150-250g，注意营养均衡，避免肥胖",
        "forbidden_foods": ["葡萄", "巧克力", "洋葱", "大蒜"],
        "recommended_food": "小型犬专用粮，注意控制卡路里",
        "common_diseases": ["过敏性皮肤病", "髌骨脱位", "眼部疾病", "青光眼"],
        "vaccine_schedule": "幼犬按标准程序接种，成年后每年加强",
        "grooming": "每周梳毛2次，换毛期加频，每月洗澡1次",
        "tags": ["小型犬", "非运动犬", "中等活跃度", "适合公寓"],
        "image_url": "",
        "description": "柴犬是日本最古老的犬种之一，外形可爱似狐狸，性格独立，是近年来网络上的超级明星。"
    },
    {
        "breed_id": "006",
        "name_zh": "边境牧羊犬",
        "name_en": "Border Collie",
        "origin": "英国苏格兰/威尔士边境",
        "size": "中型犬",
        "weight_range": "14-20 kg",
        "height_range": "46-56 cm",
        "lifespan": "12-15年",
        "personality": ["极度聪明", "工作狂", "精力充沛", "敏感"],
        "coat_color": ["黑白", "红白", "三色", "蓝灰"],
        "coat_length": "中长",
        "shedding": "中高",
        "exercise_need": "极高",
        "feeding_tips": "每日进食量约300-400g，需要高能量食物以支持高强度运动",
        "forbidden_foods": ["葡萄", "巧克力", "洋葱"],
        "recommended_food": "高能量运动犬粮",
        "common_diseases": ["髋关节发育不良", "眼部疾病（collie eye anomaly）", "癫痫"],
        "vaccine_schedule": "标准接种程序，每年加强",
        "grooming": "每周梳毛3次，每月洗澡",
        "tags": ["中型犬", "牧羊犬", "极高活跃度", "需要大量运动", "最聪明犬种"],
        "image_url": "",
        "description": "边境牧羊犬被公认为世界上最聪明的犬种，精力充沛，需要大量运动和脑力刺激。"
    },
    {
        "breed_id": "007",
        "name_zh": "贵宾犬",
        "name_en": "Poodle",
        "origin": "法国/德国",
        "size": "多种（玩具/迷你/标准）",
        "weight_range": "2-32 kg（视类型）",
        "height_range": "24-60 cm（视类型）",
        "lifespan": "12-18年",
        "personality": ["聪明", "活泼", "友善", "适应性强"],
        "coat_color": ["黑", "白", "杏色", "棕色", "灰色"],
        "coat_length": "卷曲",
        "shedding": "极低",
        "exercise_need": "中高",
        "feeding_tips": "视体型而定，标准贵宾每日约300g，玩具贵宾约80-100g",
        "forbidden_foods": ["葡萄", "巧克力", "咖啡因"],
        "recommended_food": "对应体型专用犬粮",
        "common_diseases": ["髌骨脱位（小型）", "髋关节问题（标准）", "眼部疾病", "皮肤病"],
        "vaccine_schedule": "标准程序，每年加强",
        "grooming": "每6-8周专业美容修剪，每周梳毛，每月洗澡",
        "tags": ["多种体型", "非运动犬", "低掉毛", "适合过敏者", "聪明"],
        "image_url": "",
        "description": "贵宾犬是极其聪明且几乎不掉毛的犬种，有玩具型、迷你型和标准型三种，非常适合城市家庭。"
    },
    {
        "breed_id": "008",
        "name_zh": "法国斗牛犬",
        "name_en": "French Bulldog",
        "origin": "法国",
        "size": "小型犬",
        "weight_range": "8-14 kg",
        "height_range": "28-33 cm",
        "lifespan": "10-12年",
        "personality": ["温顺", "好玩", "警觉", "忠诚"],
        "coat_color": ["淡黄褐色", "虎斑", "白色", "黑色"],
        "coat_length": "短",
        "shedding": "低",
        "exercise_need": "低",
        "feeding_tips": "每日进食量约200-250g，易肥胖，需严格控制饮食",
        "forbidden_foods": ["葡萄", "巧克力", "洋葱", "高脂食物"],
        "recommended_food": "小型短鼻犬专用粮",
        "common_diseases": ["呼吸道问题（短吻综合征）", "椎间盘疾病", "皮肤褶皱感染", "眼部问题"],
        "vaccine_schedule": "标准程序接种",
        "grooming": "每周梳毛1次，注意清洁面部褶皱，每月洗澡",
        "tags": ["小型犬", "伴侣犬", "低活跃度", "适合公寓", "不耐热"],
        "image_url": "",
        "description": "法国斗牛犬是近年来最受欢迎的城市犬之一，体型小巧，不需要大量运动，适合公寓生活。"
    },
    {
        "breed_id": "009",
        "name_zh": "英国斗牛犬",
        "name_en": "English Bulldog",
        "origin": "英国",
        "size": "中型犬",
        "weight_range": "18-25 kg",
        "height_range": "31-40 cm",
        "lifespan": "8-10年",
        "personality": ["温顺", "友善", "顽固", "勇敢"],
        "coat_color": ["虎斑", "红色", "白色", "淡黄"],
        "coat_length": "短",
        "shedding": "低",
        "exercise_need": "低",
        "feeding_tips": "每日进食量约300g，严格控制体重",
        "forbidden_foods": ["葡萄", "巧克力", "高脂肪食物"],
        "recommended_food": "短鼻犬专用犬粮",
        "common_diseases": ["呼吸道问题", "皮肤病", "髋关节问题", "眼部问题"],
        "vaccine_schedule": "标准程序接种",
        "grooming": "每周梳毛，定期清洁面部褶皱",
        "tags": ["中型犬", "伴侣犬", "低活跃度", "适合公寓"],
        "image_url": "",
        "description": "英国斗牛犬外表粗犷但性格温顺，是英国的象征性犬种，非常适合家庭饲养。"
    },
    {
        "breed_id": "010",
        "name_zh": "阿拉斯加雪橇犬",
        "name_en": "Alaskan Malamute",
        "origin": "美国阿拉斯加",
        "size": "大型犬",
        "weight_range": "34-43 kg",
        "height_range": "58-64 cm",
        "lifespan": "10-14年",
        "personality": ["友善", "忠诚", "顽皮", "独立"],
        "coat_color": ["灰白", "黑白", "红白", "棕白"],
        "coat_length": "厚双层",
        "shedding": "极高",
        "exercise_need": "高",
        "feeding_tips": "每日进食量约500-600g，高蛋白饮食",
        "forbidden_foods": ["葡萄", "巧克力", "洋葱"],
        "recommended_food": "大型工作犬高能量犬粮",
        "common_diseases": ["髋关节发育不良", "遗传性多发性神经病", "糖尿病"],
        "vaccine_schedule": "标准程序接种，每年加强",
        "grooming": "每周梳毛3-4次，换毛期每天，每月洗澡",
        "tags": ["大型犬", "工作犬", "高活跃度", "不适合热带气候"],
        "image_url": "",
        "description": "阿拉斯加雪橇犬是北极地区最古老的雪橇犬品种之一，体型比哈士奇更大，力量更强。"
    },
    {
        "breed_id": "011",
        "name_zh": "萨摩耶犬",
        "name_en": "Samoyed",
        "origin": "俄罗斯西伯利亚",
        "size": "中大型犬",
        "weight_range": "16-30 kg",
        "height_range": "46-60 cm",
        "lifespan": "12-14年",
        "personality": ["温顺友善", "活泼", "聪明", "好奇心强"],
        "coat_color": ["纯白", "奶白", "饼干色"],
        "coat_length": "长厚双层",
        "shedding": "极高",
        "exercise_need": "高",
        "feeding_tips": "每日进食量约350-450g",
        "forbidden_foods": ["葡萄", "巧克力", "洋葱"],
        "recommended_food": "高蛋白犬粮，补充鱼油",
        "common_diseases": ["遗传性肾小球病", "糖尿病", "髋关节问题", "心脏病"],
        "vaccine_schedule": "标准程序接种",
        "grooming": "每天梳毛，换毛期加频，每月洗澡",
        "tags": ["中大型犬", "工作犬", "高活跃度", "笑脸犬"],
        "image_url": "",
        "description": "萨摩耶犬以其标志性的\"微笑\"表情和雪白毛发著称，被称为\"微笑天使\"。"
    },
    {
        "breed_id": "012",
        "name_zh": "博美犬",
        "name_en": "Pomeranian",
        "origin": "德国/波兰",
        "size": "玩具犬",
        "weight_range": "1.8-3.2 kg",
        "height_range": "18-24 cm",
        "lifespan": "12-16年",
        "personality": ["活泼好奇", "聪明", "自信", "话多"],
        "coat_color": ["橙色", "红色", "白色", "黑色", "奶油色"],
        "coat_length": "长双层",
        "shedding": "中",
        "exercise_need": "低",
        "feeding_tips": "每日进食量约60-100g，小型犬高卡路里食物",
        "forbidden_foods": ["葡萄", "巧克力", "洋葱"],
        "recommended_food": "小型玩具犬专用粮",
        "common_diseases": ["气管塌陷", "髌骨脱位", "牙齿问题", "低血糖（幼犬）"],
        "vaccine_schedule": "标准程序接种",
        "grooming": "每天梳毛，每月专业美容，每3-4周洗澡",
        "tags": ["玩具犬", "伴侣犬", "低活跃度", "适合公寓", "话多"],
        "image_url": "",
        "description": "博美犬是最受欢迎的玩具犬种之一，外形如毛球，性格活泼，充满自信。"
    },
    {
        "breed_id": "013",
        "name_zh": "柯基犬",
        "name_en": "Corgi",
        "origin": "英国威尔士",
        "size": "小中型犬",
        "weight_range": "9-14 kg",
        "height_range": "25-30 cm",
        "lifespan": "12-15年",
        "personality": ["聪明机警", "友善", "勇敢", "爱玩"],
        "coat_color": ["红色", "棕色", "三色", "貂色"],
        "coat_length": "中等双层",
        "shedding": "高",
        "exercise_need": "中高",
        "feeding_tips": "每日进食量约180-250g，注意控制体重",
        "forbidden_foods": ["葡萄", "巧克力", "洋葱"],
        "recommended_food": "小中型犬专用粮",
        "common_diseases": ["椎间盘疾病（长背犬）", "髋关节发育不良", "渐进性视网膜萎缩"],
        "vaccine_schedule": "标准程序接种",
        "grooming": "每周梳毛2-3次，每月洗澡",
        "tags": ["小中型犬", "牧羊犬", "中高活跃度", "适合家庭", "英国王室御用"],
        "image_url": "",
        "description": "柯基犬因英国女王伊丽莎白二世的喜爱而闻名，短腿长身，性格聪明友善。"
    },
    {
        "breed_id": "014",
        "name_zh": "比格犬",
        "name_en": "Beagle",
        "origin": "英国",
        "size": "小中型犬",
        "weight_range": "9-11 kg",
        "height_range": "33-41 cm",
        "lifespan": "12-15年",
        "personality": ["温顺", "好奇", "活跃", "爱叫"],
        "coat_color": ["三色（黑棕白）", "棕白", "红白"],
        "coat_length": "短",
        "shedding": "中",
        "exercise_need": "高",
        "feeding_tips": "每日进食量约200-270g，易肥胖",
        "forbidden_foods": ["葡萄", "巧克力", "洋葱"],
        "recommended_food": "中型犬控体重犬粮",
        "common_diseases": ["肥胖", "椎间盘疾病", "耳道感染", "眼部问题"],
        "vaccine_schedule": "标准程序接种",
        "grooming": "每周梳毛，定期清洁耳道，每月洗澡",
        "tags": ["小中型犬", "猎犬", "高活跃度", "嗅觉灵敏", "适合家庭"],
        "image_url": "",
        "description": "比格犬嗅觉极其灵敏，是著名的猎犬，也是广受欢迎的家庭犬，性格温顺好玩。"
    },
    {
        "breed_id": "015",
        "name_zh": "约克夏梗",
        "name_en": "Yorkshire Terrier",
        "origin": "英国约克郡",
        "size": "玩具犬",
        "weight_range": "2-3.2 kg",
        "height_range": "20-23 cm",
        "lifespan": "13-16年",
        "personality": ["勇敢", "活泼", "固执", "聪明"],
        "coat_color": ["钢蓝色与棕褐色"],
        "coat_length": "长直",
        "shedding": "极低",
        "exercise_need": "低",
        "feeding_tips": "每日进食量约60-90g",
        "forbidden_foods": ["葡萄", "巧克力"],
        "recommended_food": "玩具犬专用高卡路里粮",
        "common_diseases": ["气管塌陷", "髌骨脱位", "牙周病", "低血糖"],
        "vaccine_schedule": "标准程序接种",
        "grooming": "每天梳毛，每3-4周专业美容，每2周洗澡",
        "tags": ["玩具犬", "梗类", "低活跃度", "低掉毛", "适合公寓"],
        "image_url": "",
        "description": "约克夏梗是世界上最受欢迎的玩具犬之一，虽然体型娇小但性格勇敢，几乎不掉毛。"
    },
    {
        "breed_id": "016",
        "name_zh": "马尔济斯犬",
        "name_en": "Maltese",
        "origin": "地中海马耳他岛",
        "size": "玩具犬",
        "weight_range": "2-4 kg",
        "height_range": "21-25 cm",
        "lifespan": "12-15年",
        "personality": ["温柔", "活泼", "聪明", "爱撒娇"],
        "coat_color": ["纯白"],
        "coat_length": "长直丝滑",
        "shedding": "极低",
        "exercise_need": "低",
        "feeding_tips": "每日进食量约60-90g",
        "forbidden_foods": ["葡萄", "巧克力"],
        "recommended_food": "玩具犬专用粮",
        "common_diseases": ["气管塌陷", "髌骨脱位", "泪痕", "牙齿问题"],
        "vaccine_schedule": "标准程序接种",
        "grooming": "每天梳毛，每3-4周美容，注意清洁眼部",
        "tags": ["玩具犬", "伴侣犬", "低活跃度", "低掉毛", "长毛"],
        "image_url": "",
        "description": "马尔济斯犬是古老的玩具犬种，全身雪白如云，性格温柔，是理想的伴侣犬。"
    },
    {
        "breed_id": "017",
        "name_zh": "松狮犬",
        "name_en": "Chow Chow",
        "origin": "中国",
        "size": "中大型犬",
        "weight_range": "20-32 kg",
        "height_range": "43-51 cm",
        "lifespan": "9-15年",
        "personality": ["高冷独立", "忠诚护家", "固执", "不爱社交"],
        "coat_color": ["红色", "黑色", "蓝色", "肉桂色", "奶油色"],
        "coat_length": "厚长双层",
        "shedding": "高",
        "exercise_need": "中",
        "feeding_tips": "每日进食量约350-450g",
        "forbidden_foods": ["葡萄", "巧克力"],
        "recommended_food": "大型犬专用粮",
        "common_diseases": ["髋关节发育不良", "眼睑内翻", "甲状腺问题", "皮肤病"],
        "vaccine_schedule": "标准程序接种",
        "grooming": "每周梳毛3-4次，每月洗澡",
        "tags": ["中大型犬", "非运动犬", "中活跃度", "中国原产", "独立性强"],
        "image_url": "",
        "description": "松狮犬是中国原产的古老犬种，以其蓝紫色舌头和狮子般外表著称，性格高冷独立。"
    },
    {
        "breed_id": "018",
        "name_zh": "中华田园犬",
        "name_en": "Chinese Rural Dog",
        "origin": "中国",
        "size": "小中型犬",
        "weight_range": "10-25 kg",
        "height_range": "40-55 cm",
        "lifespan": "13-16年",
        "personality": ["聪明警觉", "忠诚", "适应性强", "不娇气"],
        "coat_color": ["黄色", "黑色", "白色", "杂色"],
        "coat_length": "短中",
        "shedding": "中",
        "exercise_need": "中高",
        "feeding_tips": "每日进食量约200-300g，食物适应性强",
        "forbidden_foods": ["葡萄", "巧克力"],
        "recommended_food": "普通犬粮即可，需保证营养均衡",
        "common_diseases": ["相对健康，遗传病少", "皮肤寄生虫（农村）", "外伤"],
        "vaccine_schedule": "狂犬病疫苗必须接种，建议接种综合疫苗",
        "grooming": "每月洗澡，定期驱虫",
        "tags": ["小中型犬", "伴侣犬", "高适应性", "中国原产", "抗病力强"],
        "image_url": "",
        "description": "中华田园犬是中国土生土长的犬种，聪明忠诚，适应性极强，是中国传统的伴侣犬。"
    },
    {
        "breed_id": "019",
        "name_zh": "泰迪犬（玩具贵宾）",
        "name_en": "Teddy (Toy Poodle)",
        "origin": "法国",
        "size": "玩具犬",
        "weight_range": "2-4 kg",
        "height_range": "24-28 cm",
        "lifespan": "14-18年",
        "personality": ["聪明活泼", "友善", "适应性强", "爱撒娇"],
        "coat_color": ["杏色", "棕色", "黑色", "白色", "银色"],
        "coat_length": "卷曲",
        "shedding": "极低",
        "exercise_need": "中",
        "feeding_tips": "每日进食量约80-100g",
        "forbidden_foods": ["葡萄", "巧克力"],
        "recommended_food": "玩具犬专用粮",
        "common_diseases": ["髌骨脱位", "渐进性视网膜萎缩", "牙齿问题"],
        "vaccine_schedule": "标准程序接种",
        "grooming": "每6-8周专业美容，每周梳毛",
        "tags": ["玩具犬", "伴侣犬", "低掉毛", "适合过敏者", "聪明"],
        "image_url": "",
        "description": "泰迪犬即玩具贵宾犬，是中国最受欢迎的宠物犬之一，几乎不掉毛，非常适合城市家庭。"
    },
    {
        "breed_id": "020",
        "name_zh": "比熊犬",
        "name_en": "Bichon Frise",
        "origin": "地中海地区",
        "size": "小型犬",
        "weight_range": "5-10 kg",
        "height_range": "23-30 cm",
        "lifespan": "12-15年",
        "personality": ["活泼开朗", "友善", "温顺", "爱玩"],
        "coat_color": ["纯白"],
        "coat_length": "卷曲蓬松",
        "shedding": "极低",
        "exercise_need": "中",
        "feeding_tips": "每日进食量约100-150g",
        "forbidden_foods": ["葡萄", "巧克力"],
        "recommended_food": "小型犬专用粮",
        "common_diseases": ["膀胱结石", "皮肤过敏", "牙周病", "髌骨脱位"],
        "vaccine_schedule": "标准程序接种",
        "grooming": "每6-8周专业美容，每周梳毛",
        "tags": ["小型犬", "伴侣犬", "低掉毛", "适合公寓", "白色"],
        "image_url": "",
        "description": "比熊犬如棉花糖般可爱，几乎不掉毛，性格开朗友善，是非常受欢迎的城市伴侣犬。"
    },
    {
        "breed_id": "021",
        "name_zh": "杜宾犬",
        "name_en": "Doberman Pinscher",
        "origin": "德国",
        "size": "大型犬",
        "weight_range": "27-45 kg",
        "height_range": "63-72 cm",
        "lifespan": "10-13年",
        "personality": ["忠诚", "聪明", "勇敢", "保护性强"],
        "coat_color": ["黑棕", "红棕", "蓝棕", "驼棕"],
        "coat_length": "短",
        "shedding": "低",
        "exercise_need": "高",
        "feeding_tips": "每日进食量约500-600g，高蛋白饮食",
        "forbidden_foods": ["葡萄", "巧克力"],
        "recommended_food": "大型工作犬专用粮",
        "common_diseases": ["心肌病", "冯维勒布兰德病", "颈椎脊椎脊髓病"],
        "vaccine_schedule": "标准程序接种",
        "grooming": "每周梳毛，每月洗澡",
        "tags": ["大型犬", "工作犬", "高活跃度", "护卫犬", "需要训练"],
        "image_url": "",
        "description": "杜宾犬是著名的护卫犬，外表威武，聪明忠诚，需要良好的训练和社会化。"
    },
    {
        "breed_id": "022",
        "name_zh": "罗威纳犬",
        "name_en": "Rottweiler",
        "origin": "德国",
        "size": "大型犬",
        "weight_range": "36-61 kg",
        "height_range": "56-69 cm",
        "lifespan": "8-10年",
        "personality": ["忠诚", "自信", "冷静", "保护欲强"],
        "coat_color": ["黑色带棕褐色斑纹"],
        "coat_length": "短",
        "shedding": "中",
        "exercise_need": "高",
        "feeding_tips": "每日进食量约600-700g",
        "forbidden_foods": ["葡萄", "巧克力"],
        "recommended_food": "大型犬高蛋白犬粮",
        "common_diseases": ["髋关节和肘关节发育不良", "骨肉瘤", "心脏病"],
        "vaccine_schedule": "标准程序接种",
        "grooming": "每周梳毛，每月洗澡",
        "tags": ["大型犬", "工作犬", "高活跃度", "护卫犬", "需要训练"],
        "image_url": "",
        "description": "罗威纳犬是强壮有力的工作犬，忠诚勇敢，是出色的护卫犬和警用犬。"
    },
    {
        "breed_id": "023",
        "name_zh": "雪纳瑞",
        "name_en": "Schnauzer",
        "origin": "德国",
        "size": "小中大型（迷你/标准/巨型）",
        "weight_range": "4-48 kg（视类型）",
        "height_range": "30-70 cm（视类型）",
        "lifespan": "12-16年",
        "personality": ["聪明", "活泼", "忠诚", "机警"],
        "coat_color": ["椒盐色", "黑色", "黑银色"],
        "coat_length": "硬粗双层",
        "shedding": "极低",
        "exercise_need": "中高",
        "feeding_tips": "视体型而定，迷你雪纳瑞每日约120-160g",
        "forbidden_foods": ["葡萄", "巧克力", "高脂食物（易胰腺炎）"],
        "recommended_food": "对应体型低脂犬粮",
        "common_diseases": ["胰腺炎", "皮肤病", "白内障", "尿结石"],
        "vaccine_schedule": "标准程序接种",
        "grooming": "每6-8周专业美容，保持胡须清洁",
        "tags": ["多种体型", "梗类", "中高活跃度", "低掉毛", "胡须"],
        "image_url": "",
        "description": "雪纳瑞以其标志性的胡须和眉毛著称，有迷你、标准和巨型三种，几乎不掉毛。"
    },
    {
        "breed_id": "024",
        "name_zh": "苏格兰牧羊犬",
        "name_en": "Collie",
        "origin": "苏格兰",
        "size": "大型犬",
        "weight_range": "23-34 kg",
        "height_range": "51-61 cm",
        "lifespan": "12-14年",
        "personality": ["聪明", "温和", "忠诚", "保护性"],
        "coat_color": ["棕白", "三色", "蓝灰"],
        "coat_length": "长厚",
        "shedding": "高",
        "exercise_need": "高",
        "feeding_tips": "每日进食量约350-450g",
        "forbidden_foods": ["葡萄", "巧克力", "某些驱虫药（MDR1基因）"],
        "recommended_food": "大型犬专用粮",
        "common_diseases": ["collie眼异常", "MDR1基因突变（某些药物敏感）", "髋关节问题"],
        "vaccine_schedule": "标准程序接种",
        "grooming": "每周梳毛3-4次，每月洗澡",
        "tags": ["大型犬", "牧羊犬", "高活跃度", "适合家庭", "Lassie"],
        "image_url": "",
        "description": "苏格兰牧羊犬因电影《灵犬莱西》而闻名全球，聪明温顺，是优秀的家庭犬和牧羊犬。"
    },
    {
        "breed_id": "025",
        "name_zh": "澳大利亚牧羊犬",
        "name_en": "Australian Shepherd",
        "origin": "美国（非澳大利亚）",
        "size": "中型犬",
        "weight_range": "16-32 kg",
        "height_range": "46-58 cm",
        "lifespan": "12-15年",
        "personality": ["精力旺盛", "聪明", "工作狂", "爱粘人"],
        "coat_color": ["蓝色大理石花纹", "红色大理石花纹", "黑色", "红色"],
        "coat_length": "中长",
        "shedding": "高",
        "exercise_need": "极高",
        "feeding_tips": "每日进食量约350-450g，高能量食物",
        "forbidden_foods": ["葡萄", "巧克力"],
        "recommended_food": "运动犬高能量粮",
        "common_diseases": ["MDR1基因突变", "髋关节问题", "眼部疾病", "癫痫"],
        "vaccine_schedule": "标准程序接种",
        "grooming": "每周梳毛3-4次，每月洗澡",
        "tags": ["中型犬", "牧羊犬", "极高活跃度", "大理石花纹"],
        "image_url": "",
        "description": "澳大利亚牧羊犬是精力极其旺盛的工作犬，以其多彩的大理石花纹毛色著称。"
    },
    {
        "breed_id": "026",
        "name_zh": "大丹犬",
        "name_en": "Great Dane",
        "origin": "德国",
        "size": "超大型犬",
        "weight_range": "45-90 kg",
        "height_range": "71-86 cm",
        "lifespan": "7-10年",
        "personality": ["温和友善", "忠诚", "耐心", "警觉"],
        "coat_color": ["浅黄褐色", "虎斑", "黑色", "蓝色", "Harlequin"],
        "coat_length": "短",
        "shedding": "中",
        "exercise_need": "中",
        "feeding_tips": "每日进食量约600-800g，需要大型犬专用粮防止骨骼问题",
        "forbidden_foods": ["葡萄", "巧克力"],
        "recommended_food": "超大型犬专用粮（低钙磷比）",
        "common_diseases": ["胃扭转（致命）", "心肌病", "骨肉瘤", "骨关节炎"],
        "vaccine_schedule": "标准程序接种",
        "grooming": "每周梳毛，每月洗澡",
        "tags": ["超大型犬", "工作犬", "中活跃度", "温柔巨人"],
        "image_url": "",
        "description": "大丹犬是世界上最高大的犬种之一，外表威武但性格温和，被称为\"温柔的巨人\"。"
    },
    {
        "breed_id": "027",
        "name_zh": "哈瓦那犬",
        "name_en": "Havanese",
        "origin": "古巴",
        "size": "玩具犬",
        "weight_range": "3-6 kg",
        "height_range": "23-27 cm",
        "lifespan": "14-16年",
        "personality": ["活泼", "聪明", "友善", "不爱独处"],
        "coat_color": ["黑色", "白色", "蓝色", "银色", "奶油色"],
        "coat_length": "长软丝状",
        "shedding": "低",
        "exercise_need": "低",
        "feeding_tips": "每日进食量约80-120g",
        "forbidden_foods": ["葡萄", "巧克力"],
        "recommended_food": "玩具犬专用粮",
        "common_diseases": ["髌骨脱位", "白内障", "肝脏疾病"],
        "vaccine_schedule": "标准程序接种",
        "grooming": "每天梳毛，每3-4周美容",
        "tags": ["玩具犬", "伴侣犬", "低活跃度", "低掉毛", "古巴国犬"],
        "image_url": "",
        "description": "哈瓦那犬是古巴的国犬，活泼友善，特别喜欢和人在一起，不适合长期独处。"
    },
    {
        "breed_id": "028",
        "name_zh": "西施犬",
        "name_en": "Shih Tzu",
        "origin": "中国/西藏",
        "size": "玩具犬",
        "weight_range": "4-7 kg",
        "height_range": "20-28 cm",
        "lifespan": "10-16年",
        "personality": ["温柔", "友善", "开朗", "爱依人"],
        "coat_color": ["金色", "白色", "棕色", "黑色", "杂色"],
        "coat_length": "长直双层",
        "shedding": "低",
        "exercise_need": "低",
        "feeding_tips": "每日进食量约100-150g",
        "forbidden_foods": ["葡萄", "巧克力"],
        "recommended_food": "小型犬专用粮",
        "common_diseases": ["呼吸道问题（短吻）", "眼部问题", "肾脏问题", "椎间盘疾病"],
        "vaccine_schedule": "标准程序接种",
        "grooming": "每天梳毛，每3-4周美容，注意清洁眼部",
        "tags": ["玩具犬", "伴侣犬", "低活跃度", "低掉毛", "中国原产"],
        "image_url": "",
        "description": "西施犬源自中国皇宫，外形高贵优雅，性格温柔友善，是理想的城市伴侣犬。"
    },
    {
        "breed_id": "029",
        "name_zh": "巴哥犬",
        "name_en": "Pug",
        "origin": "中国",
        "size": "小型犬",
        "weight_range": "6-8 kg",
        "height_range": "25-33 cm",
        "lifespan": "12-15年",
        "personality": ["调皮可爱", "友善", "平静", "爱笑"],
        "coat_color": ["浅黄褐色", "黑色", "银色"],
        "coat_length": "短细",
        "shedding": "高（相对体型）",
        "exercise_need": "低",
        "feeding_tips": "每日进食量约150-200g，严格控制体重",
        "forbidden_foods": ["葡萄", "巧克力", "高脂食物"],
        "recommended_food": "小型短吻犬专用控重粮",
        "common_diseases": ["呼吸道问题", "眼部问题（角膜溃疡）", "神经系统退化"],
        "vaccine_schedule": "标准程序接种",
        "grooming": "每周梳毛，清洁面部褶皱，每月洗澡",
        "tags": ["小型犬", "伴侣犬", "低活跃度", "不耐热", "中国原产"],
        "image_url": "",
        "description": "巴哥犬（哈巴狗）源自中国，以其皱褶面孔和卷曲尾巴著称，性格开朗有趣。"
    },
    {
        "breed_id": "030",
        "name_zh": "秋田犬",
        "name_en": "Akita",
        "origin": "日本",
        "size": "大型犬",
        "weight_range": "32-59 kg",
        "height_range": "58-70 cm",
        "lifespan": "10-15年",
        "personality": ["忠诚", "独立", "尊严感强", "保护性"],
        "coat_color": ["红色", "白色", "芝麻色", "虎斑"],
        "coat_length": "厚双层",
        "shedding": "高",
        "exercise_need": "高",
        "feeding_tips": "每日进食量约400-500g",
        "forbidden_foods": ["葡萄", "巧克力", "洋葱（毒性更强）"],
        "recommended_food": "大型犬高蛋白粮",
        "common_diseases": ["甲状腺功能减退", "髋关节发育不良", "免疫系统疾病"],
        "vaccine_schedule": "标准程序接种",
        "grooming": "每周梳毛2-3次，换毛期每天，每月洗澡",
        "tags": ["大型犬", "工作犬", "高活跃度", "日本原产", "忠犬八公"],
        "image_url": "",
        "description": "秋田犬是日本最著名的犬种，因\"忠犬八公\"的故事而享誉全球，象征忠诚和好运。"
    },
    # 继续添加更多品种...
    {
        "breed_id": "031",
        "name_zh": "腊肠犬",
        "name_en": "Dachshund",
        "origin": "德国",
        "size": "小型犬",
        "weight_range": "5-11 kg（标准）/ 3-5 kg（迷你）",
        "height_range": "20-23 cm",
        "lifespan": "12-16年",
        "personality": ["顽固", "好奇", "活泼", "勇敢"],
        "coat_color": ["红色", "黑棕", "巧克力棕", "奶油色"],
        "coat_length": "短/长/刚毛（三种）",
        "shedding": "低",
        "exercise_need": "中",
        "feeding_tips": "每日进食量约150-200g，严格控重防脊柱问题",
        "forbidden_foods": ["葡萄", "巧克力"],
        "recommended_food": "小型犬低卡路里粮",
        "common_diseases": ["椎间盘疾病（最易发）", "髌骨脱位", "渐进性视网膜萎缩"],
        "vaccine_schedule": "标准程序接种",
        "grooming": "视毛型，短毛每周梳1次，长毛每天梳",
        "tags": ["小型犬", "猎犬", "中活跃度", "长身短腿", "顽固"],
        "image_url": "",
        "description": "腊肠犬以其超长的身体和短腿著称，是非常受欢迎的小型犬，但需注意保护其脊柱。"
    },
    {
        "breed_id": "032",
        "name_zh": "西藏獒",
        "name_en": "Tibetan Mastiff",
        "origin": "中国西藏",
        "size": "超大型犬",
        "weight_range": "45-90 kg",
        "height_range": "61-76 cm",
        "lifespan": "10-14年",
        "personality": ["独立", "保护性强", "忠诚", "警觉"],
        "coat_color": ["黑色", "棕色", "蓝灰", "金色"],
        "coat_length": "厚长双层",
        "shedding": "高",
        "exercise_need": "中",
        "feeding_tips": "每日进食量约600-800g",
        "forbidden_foods": ["葡萄", "巧克力"],
        "recommended_food": "超大型犬专用粮",
        "common_diseases": ["髋关节发育不良", "甲状腺功能减退", "自身免疫性疾病"],
        "vaccine_schedule": "标准程序接种",
        "grooming": "每周梳毛3-4次，换毛期每天",
        "tags": ["超大型犬", "工作犬", "中活跃度", "中国原产", "守护犬"],
        "image_url": "",
        "description": "藏獒是来自中国西藏的古老犬种，是世界上最大、最有力量的犬种之一，天生的守护者。"
    },
    {
        "breed_id": "033",
        "name_zh": "喜乐蒂牧羊犬",
        "name_en": "Shetland Sheepdog",
        "origin": "苏格兰设得兰群岛",
        "size": "小中型犬",
        "weight_range": "6-12 kg",
        "height_range": "33-41 cm",
        "lifespan": "12-14年",
        "personality": ["聪明", "活泼", "温顺", "敏感"],
        "coat_color": ["棕白", "黑白棕（三色）", "蓝色大理石"],
        "coat_length": "长厚双层",
        "shedding": "高",
        "exercise_need": "高",
        "feeding_tips": "每日进食量约180-250g",
        "forbidden_foods": ["葡萄", "巧克力", "某些驱虫药（MDR1基因）"],
        "recommended_food": "小中型犬专用粮",
        "common_diseases": ["MDR1基因突变", "Collie眼异常", "髌骨脱位", "癫痫"],
        "vaccine_schedule": "标准程序接种",
        "grooming": "每周梳毛3-4次，每月洗澡",
        "tags": ["小中型犬", "牧羊犬", "高活跃度", "聪明", "长毛"],
        "image_url": "",
        "description": "喜乐蒂牧羊犬外形似迷你苏格兰牧羊犬，聪明温顺，是受欢迎的家庭犬。"
    },
    {
        "breed_id": "034",
        "name_zh": "斗牛梗",
        "name_en": "Bull Terrier",
        "origin": "英国",
        "size": "中型犬",
        "weight_range": "20-36 kg",
        "height_range": "53-56 cm",
        "lifespan": "10-14年",
        "personality": ["活泼", "顽皮", "固执", "勇敢"],
        "coat_color": ["白色", "虎斑", "红色", "黑色"],
        "coat_length": "短",
        "shedding": "低",
        "exercise_need": "高",
        "feeding_tips": "每日进食量约300-400g",
        "forbidden_foods": ["葡萄", "巧克力"],
        "recommended_food": "中型犬高蛋白粮",
        "common_diseases": ["皮肤过敏", "心脏问题", "肾脏问题", "耳聋（白色个体）"],
        "vaccine_schedule": "标准程序接种",
        "grooming": "每周梳毛，每月洗澡",
        "tags": ["中型犬", "梗类", "高活跃度", "鸡蛋脸", "需要训练"],
        "image_url": "",
        "description": "斗牛梗以其独特的鸡蛋形头部著称，性格顽皮勇敢，需要良好的训练和社会化。"
    },
    {
        "breed_id": "035",
        "name_zh": "杰克罗素梗",
        "name_en": "Jack Russell Terrier",
        "origin": "英国",
        "size": "小型犬",
        "weight_range": "5-8 kg",
        "height_range": "25-38 cm",
        "lifespan": "13-16年",
        "personality": ["精力充沛", "聪明", "勇敢", "顽皮"],
        "coat_color": ["白色带棕斑", "白色带黑斑", "三色"],
        "coat_length": "短（平毛/硬毛）",
        "shedding": "中",
        "exercise_need": "高",
        "feeding_tips": "每日进食量约100-150g",
        "forbidden_foods": ["葡萄", "巧克力"],
        "recommended_food": "小型活动犬专用高能量粮",
        "common_diseases": ["髌骨脱位", "眼部疾病", "耳聋（白色个体）", "莱格-佩特斯病"],
        "vaccine_schedule": "标准程序接种",
        "grooming": "每周梳毛，每月洗澡",
        "tags": ["小型犬", "梗类", "高活跃度", "精力旺盛", "需要运动"],
        "image_url": "",
        "description": "杰克罗素梗是精力旺盛的小型梗犬，活泼好动，需要大量运动和脑力刺激。"
    },
    {
        "breed_id": "036",
        "name_zh": "西高地白梗",
        "name_en": "West Highland White Terrier",
        "origin": "苏格兰",
        "size": "小型犬",
        "weight_range": "6-10 kg",
        "height_range": "25-28 cm",
        "lifespan": "13-15年",
        "personality": ["活泼", "友善", "独立", "勇敢"],
        "coat_color": ["纯白"],
        "coat_length": "硬双层",
        "shedding": "低",
        "exercise_need": "中",
        "feeding_tips": "每日进食量约150-200g",
        "forbidden_foods": ["葡萄", "巧克力"],
        "recommended_food": "小型犬专用粮",
        "common_diseases": ["皮肤病（西高地白梗皮肤综合征）", "下颌骨骨软骨病", "铜中毒风险"],
        "vaccine_schedule": "标准程序接种",
        "grooming": "每6-8周专业美容，每周梳毛",
        "tags": ["小型犬", "梗类", "中活跃度", "纯白", "低掉毛"],
        "image_url": "",
        "description": "西高地白梗（Westie）是活泼可爱的白色小型梗犬，性格开朗，充满个性。"
    },
    {
        "breed_id": "037",
        "name_zh": "凯恩梗",
        "name_en": "Cairn Terrier",
        "origin": "苏格兰",
        "size": "小型犬",
        "weight_range": "5-7 kg",
        "height_range": "25-30 cm",
        "lifespan": "12-15年",
        "personality": ["勇敢", "活泼", "顽固", "聪明"],
        "coat_color": ["奶油色", "灰色", "红色", "砂色", "棕色"],
        "coat_length": "粗糙双层",
        "shedding": "低",
        "exercise_need": "中",
        "feeding_tips": "每日进食量约130-160g",
        "forbidden_foods": ["葡萄", "巧克力"],
        "recommended_food": "小型犬专用粮",
        "common_diseases": ["髌骨脱位", "莱格-佩特斯病", "球虫病"],
        "vaccine_schedule": "标准程序接种",
        "grooming": "每6-8周专业美容",
        "tags": ["小型犬", "梗类", "中活跃度", "《绿野仙踪》Toto的原型"],
        "image_url": "",
        "description": "凯恩梗是《绿野仙踪》中小狗Toto的原型，活泼勇敢，是迷人的小型伴侣犬。"
    },
    {
        "breed_id": "038",
        "name_zh": "大白熊犬",
        "name_en": "Great Pyrenees",
        "origin": "法国/西班牙比利牛斯山",
        "size": "超大型犬",
        "weight_range": "36-54 kg",
        "height_range": "63-82 cm",
        "lifespan": "10-12年",
        "personality": ["温和", "耐心", "忠诚", "独立"],
        "coat_color": ["纯白", "白色带灰/棕斑"],
        "coat_length": "厚长双层",
        "shedding": "高",
        "exercise_need": "中",
        "feeding_tips": "每日进食量约500-700g",
        "forbidden_foods": ["葡萄", "巧克力"],
        "recommended_food": "超大型犬专用粮",
        "common_diseases": ["髋关节发育不良", "骨肉瘤", "胃扭转", "神经系统疾病"],
        "vaccine_schedule": "标准程序接种",
        "grooming": "每周梳毛3-4次，换毛期每天",
        "tags": ["超大型犬", "工作犬", "中活跃度", "牧羊护卫犬", "白色"],
        "image_url": "",
        "description": "大白熊犬是古老的牧羊护卫犬，体型巨大，毛色洁白，性格温和耐心。"
    },
    {
        "breed_id": "039",
        "name_zh": "波士顿梗",
        "name_en": "Boston Terrier",
        "origin": "美国",
        "size": "小型犬",
        "weight_range": "5-11 kg",
        "height_range": "38-43 cm",
        "lifespan": "11-15年",
        "personality": ["活泼", "友善", "聪明", "热情"],
        "coat_color": ["黑白", "虎斑白", "海豹色白"],
        "coat_length": "短",
        "shedding": "低",
        "exercise_need": "中",
        "feeding_tips": "每日进食量约150-250g",
        "forbidden_foods": ["葡萄", "巧克力"],
        "recommended_food": "小型犬专用粮",
        "common_diseases": ["呼吸道问题（短吻）", "白内障", "眼部问题", "髌骨脱位"],
        "vaccine_schedule": "标准程序接种",
        "grooming": "每周梳毛，清洁面部褶皱，每月洗澡",
        "tags": ["小型犬", "非运动犬", "中活跃度", "美国绅士犬"],
        "image_url": "",
        "description": "波士顿梗被称为\"美国绅士\"，黑白相间的外表如同穿着燕尾服，性格友善活泼。"
    },
    {
        "breed_id": "040",
        "name_zh": "爱尔兰猎狼犬",
        "name_en": "Irish Wolfhound",
        "origin": "爱尔兰",
        "size": "超大型犬",
        "weight_range": "48-70 kg",
        "height_range": "71-90 cm",
        "lifespan": "6-10年",
        "personality": ["温和", "耐心", "高贵", "忠诚"],
        "coat_color": ["灰色", "浅黄褐色", "红色", "黑色", "白色"],
        "coat_length": "粗糙线状",
        "shedding": "中",
        "exercise_need": "高",
        "feeding_tips": "每日进食量约700-900g，幼犬需特别控制生长速度",
        "forbidden_foods": ["葡萄", "巧克力"],
        "recommended_food": "超大型犬专用大颗粒粮",
        "common_diseases": ["心肌病", "胃扭转", "骨肉瘤", "肝脏疾病"],
        "vaccine_schedule": "标准程序接种",
        "grooming": "每周梳毛2-3次，每月洗澡",
        "tags": ["超大型犬", "猎犬", "高活跃度", "世界最高犬种"],
        "image_url": "",
        "description": "爱尔兰猎狼犬是世界上最高大的犬种，外表威猛但性格温和，是真正的\"温柔巨人\"。"
    },
    {
        "breed_id": "041",
        "name_zh": "威玛犬",
        "name_en": "Weimaraner",
        "origin": "德国",
        "size": "大型犬",
        "weight_range": "25-40 kg",
        "height_range": "56-68 cm",
        "lifespan": "10-13年",
        "personality": ["活泼", "聪明", "爱粘人", "精力充沛"],
        "coat_color": ["银灰色", "鼠灰色", "蓝灰色"],
        "coat_length": "短",
        "shedding": "低",
        "exercise_need": "极高",
        "feeding_tips": "每日进食量约400-500g",
        "forbidden_foods": ["葡萄", "巧克力"],
        "recommended_food": "大型运动犬高能量粮",
        "common_diseases": ["胃扭转", "髋关节发育不良", "先天性脊椎发育不良"],
        "vaccine_schedule": "标准程序接种",
        "grooming": "每周梳毛，每月洗澡",
        "tags": ["大型犬", "运动犬", "极高活跃度", "灰色幽灵", "猎犬"],
        "image_url": "",
        "description": "威玛犬以其独特的银灰色毛发被称为\"灰色幽灵\"，精力旺盛，需要大量运动。"
    },
    {
        "breed_id": "042",
        "name_zh": "布列塔尼猎犬",
        "name_en": "Brittany",
        "origin": "法国布列塔尼",
        "size": "中型犬",
        "weight_range": "14-20 kg",
        "height_range": "43-52 cm",
        "lifespan": "12-14年",
        "personality": ["活泼", "友善", "聪明", "热情"],
        "coat_color": ["橙白", "棕白", "肝白", "三色"],
        "coat_length": "中等波浪",
        "shedding": "中",
        "exercise_need": "高",
        "feeding_tips": "每日进食量约300-400g",
        "forbidden_foods": ["葡萄", "巧克力"],
        "recommended_food": "中型运动犬专用粮",
        "common_diseases": ["髋关节发育不良", "癫痫", "甲状腺问题"],
        "vaccine_schedule": "标准程序接种",
        "grooming": "每周梳毛，每月洗澡",
        "tags": ["中型犬", "运动犬", "高活跃度", "猎鸟犬"],
        "image_url": "",
        "description": "布列塔尼猎犬是法国著名的猎鸟犬，活泼友善，适合活跃的家庭。"
    },
    {
        "breed_id": "043",
        "name_zh": "巴仙吉犬",
        "name_en": "Basenji",
        "origin": "刚果",
        "size": "小中型犬",
        "weight_range": "9-11 kg",
        "height_range": "40-43 cm",
        "lifespan": "13-14年",
        "personality": ["独立", "好奇", "警觉", "聪明"],
        "coat_color": ["红色", "黑色", "棕色", "三色"],
        "coat_length": "短光滑",
        "shedding": "极低",
        "exercise_need": "高",
        "feeding_tips": "每日进食量约200-280g",
        "forbidden_foods": ["葡萄", "巧克力"],
        "recommended_food": "小中型犬专用粮",
        "common_diseases": ["Fanconi综合征（肾脏）", "渐进性视网膜萎缩", "甲状腺问题"],
        "vaccine_schedule": "标准程序接种",
        "grooming": "每周梳毛，自我清洁能力强，每月洗澡",
        "tags": ["小中型犬", "猎犬", "高活跃度", "不叫犬", "非洲犬种"],
        "image_url": "",
        "description": "巴仙吉犬是世界上唯一不会吠叫的犬种，发出独特的yodel声，是非洲古老猎犬。"
    },
    {
        "breed_id": "044",
        "name_zh": "大麦町犬",
        "name_en": "Dalmatian",
        "origin": "克罗地亚",
        "size": "中大型犬",
        "weight_range": "23-32 kg",
        "height_range": "48-61 cm",
        "lifespan": "11-13年",
        "personality": ["精力充沛", "聪明", "外向", "活泼"],
        "coat_color": ["白色带黑点", "白色带棕点"],
        "coat_length": "短",
        "shedding": "高（持续性）",
        "exercise_need": "极高",
        "feeding_tips": "每日进食量约350-450g，低嘌呤饮食（预防尿结石）",
        "forbidden_foods": ["葡萄", "巧克力", "高嘌呤食物"],
        "recommended_food": "中大型犬低嘌呤犬粮",
        "common_diseases": ["尿结石（高发）", "耳聋（约30%有遗传性耳聋）", "皮肤过敏"],
        "vaccine_schedule": "标准程序接种",
        "grooming": "每周梳毛，每月洗澡",
        "tags": ["中大型犬", "非运动犬", "极高活跃度", "斑点狗", "消防车犬"],
        "image_url": "",
        "description": "大麦町犬（斑点狗）因电影《101忠狗》而家喻户晓，精力充沛，需要大量运动。"
    },
    {
        "breed_id": "045",
        "name_zh": "可卡犬",
        "name_en": "Cocker Spaniel",
        "origin": "英国/美国",
        "size": "小中型犬",
        "weight_range": "9-14 kg",
        "height_range": "34-44 cm",
        "lifespan": "12-15年",
        "personality": ["温顺", "活泼", "爱玩", "感情丰富"],
        "coat_color": ["黑色", "金色", "棕色", "红色", "杂色"],
        "coat_length": "中长波浪",
        "shedding": "中",
        "exercise_need": "中高",
        "feeding_tips": "每日进食量约200-280g",
        "forbidden_foods": ["葡萄", "巧克力"],
        "recommended_food": "小中型犬专用粮",
        "common_diseases": ["耳道感染（长耳）", "眼部问题", "髋关节问题", "IMHA（免疫性溶血）"],
        "vaccine_schedule": "标准程序接种",
        "grooming": "每周梳毛，定期清洁耳道，每月洗澡",
        "tags": ["小中型犬", "猎犬", "中高活跃度", "长耳", "适合家庭"],
        "image_url": "",
        "description": "可卡犬（英国/美国可卡）以其美丽的长耳和丝滑毛发著称，性格温顺友善。"
    },
    {
        "breed_id": "046",
        "name_zh": "斯普林格猎犬",
        "name_en": "Springer Spaniel",
        "origin": "英国",
        "size": "中型犬",
        "weight_range": "18-25 kg",
        "height_range": "46-56 cm",
        "lifespan": "12-14年",
        "personality": ["活泼", "友善", "聪明", "服从性好"],
        "coat_color": ["棕白", "黑白", "肝白"],
        "coat_length": "中等波浪",
        "shedding": "中",
        "exercise_need": "高",
        "feeding_tips": "每日进食量约300-400g",
        "forbidden_foods": ["葡萄", "巧克力"],
        "recommended_food": "中型运动犬专用粮",
        "common_diseases": ["耳道感染", "髋关节发育不良", "眼部问题"],
        "vaccine_schedule": "标准程序接种",
        "grooming": "每周梳毛，定期清耳，每月洗澡",
        "tags": ["中型犬", "运动犬", "高活跃度", "猎鸟犬"],
        "image_url": "",
        "description": "英国史宾格猎犬是优秀的猎鸟犬，活泼友善，适合活跃的家庭生活。"
    },
    {
        "breed_id": "047",
        "name_zh": "波利犬",
        "name_en": "Puli",
        "origin": "匈牙利",
        "size": "中型犬",
        "weight_range": "10-15 kg",
        "height_range": "37-44 cm",
        "lifespan": "10-15年",
        "personality": ["聪明", "活泼", "忠诚", "护家"],
        "coat_color": ["黑色", "灰色", "白色", "棕色"],
        "coat_length": "绳状拖把",
        "shedding": "低",
        "exercise_need": "高",
        "feeding_tips": "每日进食量约250-350g",
        "forbidden_foods": ["葡萄", "巧克力"],
        "recommended_food": "中型犬专用粮",
        "common_diseases": ["髋关节发育不良", "眼部问题"],
        "vaccine_schedule": "标准程序接种",
        "grooming": "绳状毛需专业护理，避免打结缠绕",
        "tags": ["中型犬", "牧羊犬", "高活跃度", "绳状毛", "匈牙利犬种"],
        "image_url": "",
        "description": "波利犬以其独特的绳状毛发著称，看起来像一把会跑的拖把，是匈牙利著名的牧羊犬。"
    },
    {
        "breed_id": "048",
        "name_zh": "布鲁塞尔格里芬犬",
        "name_en": "Brussels Griffon",
        "origin": "比利时布鲁塞尔",
        "size": "玩具犬",
        "weight_range": "3-6 kg",
        "height_range": "18-25 cm",
        "lifespan": "12-15年",
        "personality": ["活泼", "聪明", "依恋主人", "敏感"],
        "coat_color": ["红色", "黑棕", "黑色", "棕褐色"],
        "coat_length": "粗糙/光滑（两种）",
        "shedding": "低",
        "exercise_need": "低",
        "feeding_tips": "每日进食量约80-120g",
        "forbidden_foods": ["葡萄", "巧克力"],
        "recommended_food": "玩具犬专用粮",
        "common_diseases": ["呼吸道问题（短吻）", "眼部问题", "髌骨脱位"],
        "vaccine_schedule": "标准程序接种",
        "grooming": "粗糙毛型需定期美容，光滑毛型每周梳毛",
        "tags": ["玩具犬", "伴侣犬", "低活跃度", "类人脸", "比利时犬种"],
        "image_url": "",
        "description": "布鲁塞尔格里芬犬以其类似人类的面部表情著称，充满个性，是迷人的玩具伴侣犬。"
    },
    {
        "breed_id": "049",
        "name_zh": "意大利灵缇",
        "name_en": "Italian Greyhound",
        "origin": "意大利",
        "size": "小型犬",
        "weight_range": "3-5 kg",
        "height_range": "33-38 cm",
        "lifespan": "14-15年",
        "personality": ["温柔", "敏感", "活泼", "爱依人"],
        "coat_color": ["灰色", "黑色", "黄褐色", "红色", "蓝色"],
        "coat_length": "短极细",
        "shedding": "极低",
        "exercise_need": "中高",
        "feeding_tips": "每日进食量约100-150g",
        "forbidden_foods": ["葡萄", "巧克力"],
        "recommended_food": "小型犬高卡路里粮",
        "common_diseases": ["骨折（骨骼纤细）", "牙周病", "癫痫", "甲状腺问题"],
        "vaccine_schedule": "标准程序接种",
        "grooming": "每周擦拭，每月洗澡，注意保暖",
        "tags": ["小型犬", "猎犬", "中高活跃度", "需要保暖", "极细短毛"],
        "image_url": "",
        "description": "意大利灵缇是最小的猎犬品种，骨骼纤细优雅，跑速惊人，需要注意防寒。"
    },
    {
        "breed_id": "050",
        "name_zh": "纽芬兰犬",
        "name_en": "Newfoundland",
        "origin": "加拿大纽芬兰",
        "size": "超大型犬",
        "weight_range": "45-70 kg",
        "height_range": "63-74 cm",
        "lifespan": "8-10年",
        "personality": ["温柔", "耐心", "忠诚", "爱孩子"],
        "coat_color": ["黑色", "棕色", "黑白（Landseer）", "灰色"],
        "coat_length": "厚长双层防水",
        "shedding": "极高",
        "exercise_need": "中",
        "feeding_tips": "每日进食量约600-800g，注意防止胃扭转",
        "forbidden_foods": ["葡萄", "巧克力"],
        "recommended_food": "超大型犬专用粮",
        "common_diseases": ["髋关节和肘关节发育不良", "心脏病（主动脉瓣下狭窄）", "胃扭转"],
        "vaccine_schedule": "标准程序接种",
        "grooming": "每周梳毛3-4次，每月洗澡",
        "tags": ["超大型犬", "工作犬", "中活跃度", "水上救援犬", "保姆犬"],
        "image_url": "",
        "description": "纽芬兰犬因其温柔的性格和对孩子的耐心被称为\"保姆犬\"，也是出色的水上救援犬。"
    },
    {
        "breed_id": "051",
        "name_zh": "猎狐梗",
        "name_en": "Fox Terrier",
        "origin": "英国",
        "size": "小中型犬",
        "weight_range": "7-9 kg",
        "height_range": "35-40 cm",
        "lifespan": "12-15年",
        "personality": ["勇敢", "活泼", "好奇", "固执"],
        "coat_color": ["白色带棕/黑色斑纹"],
        "coat_length": "短（平毛）/硬（刚毛）",
        "shedding": "低",
        "exercise_need": "高",
        "feeding_tips": "每日进食量约150-200g",
        "forbidden_foods": ["葡萄", "巧克力"],
        "recommended_food": "小中型犬活动粮",
        "common_diseases": ["眼部遗传疾病", "肩关节脱位", "莱格-佩特斯病"],
        "vaccine_schedule": "标准程序接种",
        "grooming": "刚毛型需定期人工拔毛（hand stripping）",
        "tags": ["小中型犬", "梗类", "高活跃度", "猎狐", "经典梗犬"],
        "image_url": "",
        "description": "猎狐梗是英国传统梗犬，勇敢活泼，历史上用于驱赶狐狸出洞，是充满个性的猎犬。"
    },
    {
        "breed_id": "052",
        "name_zh": "马里诺斯犬",
        "name_en": "Belgian Malinois",
        "origin": "比利时",
        "size": "中大型犬",
        "weight_range": "25-35 kg",
        "height_range": "56-66 cm",
        "lifespan": "12-14年",
        "personality": ["聪明", "高度警觉", "精力充沛", "工作狂"],
        "coat_color": ["浅黄褐色带黑色面具"],
        "coat_length": "短",
        "shedding": "中",
        "exercise_need": "极高",
        "feeding_tips": "每日进食量约400-500g，高蛋白工作犬食物",
        "forbidden_foods": ["葡萄", "巧克力"],
        "recommended_food": "高强度工作犬专用粮",
        "common_diseases": ["髋关节和肘关节发育不良", "进行性视网膜萎缩", "癫痫"],
        "vaccine_schedule": "标准程序接种",
        "grooming": "每周梳毛，每月洗澡",
        "tags": ["中大型犬", "牧羊犬", "极高活跃度", "警犬首选", "特种兵犬"],
        "image_url": "",
        "description": "比利时马里诺斯犬是现代最受欢迎的警用、军用犬种，智力超群，工作能力极强。"
    },
    {
        "breed_id": "053",
        "name_zh": "凯利蓝梗",
        "name_en": "Kerry Blue Terrier",
        "origin": "爱尔兰凯里郡",
        "size": "中型犬",
        "weight_range": "15-18 kg",
        "height_range": "44-49 cm",
        "lifespan": "12-15年",
        "personality": ["活泼", "聪明", "顽固", "忠诚"],
        "coat_color": ["蓝灰色（出生时黑色逐渐变蓝）"],
        "coat_length": "波浪柔软",
        "shedding": "极低",
        "exercise_need": "高",
        "feeding_tips": "每日进食量约250-320g",
        "forbidden_foods": ["葡萄", "巧克力"],
        "recommended_food": "中型犬专用粮",
        "common_diseases": ["渐进性视网膜萎缩", "小脑萎缩症", "皮肤囊肿"],
        "vaccine_schedule": "标准程序接种",
        "grooming": "每6-8周专业美容，每周梳毛",
        "tags": ["中型犬", "梗类", "高活跃度", "蓝色毛发", "爱尔兰国犬"],
        "image_url": "",
        "description": "凯利蓝梗是爱尔兰的国犬，以其独特的蓝灰色毛发著称，活泼聪明，几乎不掉毛。"
    },
    {
        "breed_id": "054",
        "name_zh": "萨路基猎犬",
        "name_en": "Saluki",
        "origin": "中东",
        "size": "大型犬",
        "weight_range": "16-29 kg",
        "height_range": "58-71 cm",
        "lifespan": "12-14年",
        "personality": ["独立", "温和", "敏感", "忠诚"],
        "coat_color": ["白色", "奶油色", "金色", "红色", "三色"],
        "coat_length": "光滑（短）/ 羽状（长耳）",
        "shedding": "低",
        "exercise_need": "高",
        "feeding_tips": "每日进食量约350-450g，细长体型需高蛋白",
        "forbidden_foods": ["葡萄", "巧克力"],
        "recommended_food": "大型猎犬专用高蛋白粮",
        "common_diseases": ["心脏病", "肿瘤", "甲状腺问题"],
        "vaccine_schedule": "标准程序接种",
        "grooming": "每周梳毛，每月洗澡",
        "tags": ["大型犬", "猎犬", "高活跃度", "古老犬种", "中东猎犬"],
        "image_url": "",
        "description": "萨路基猎犬是世界上最古老的犬种之一，来自中东，以极快的速度和优雅的外形著称。"
    },
    {
        "breed_id": "055",
        "name_zh": "卡迪根威尔士柯基",
        "name_en": "Cardigan Welsh Corgi",
        "origin": "英国威尔士",
        "size": "小中型犬",
        "weight_range": "11-17 kg",
        "height_range": "27-33 cm",
        "lifespan": "12-15年",
        "personality": ["聪明", "忠诚", "机警", "独立"],
        "coat_color": ["红色", "貂色", "虎斑", "黑色", "蓝色大理石"],
        "coat_length": "中等双层",
        "shedding": "高",
        "exercise_need": "中高",
        "feeding_tips": "每日进食量约180-240g，注意防止脊柱问题",
        "forbidden_foods": ["葡萄", "巧克力"],
        "recommended_food": "小中型犬专用粮",
        "common_diseases": ["椎间盘疾病", "渐进性视网膜萎缩", "髋关节发育不良"],
        "vaccine_schedule": "标准程序接种",
        "grooming": "每周梳毛2-3次，每月洗澡",
        "tags": ["小中型犬", "牧羊犬", "中高活跃度", "有尾巴的柯基", "威尔士"],
        "image_url": "",
        "description": "卡迪根威尔士柯基与彭布罗克柯基的主要区别是有一条长尾巴，同样矮小可爱。"
    },
    {
        "breed_id": "056",
        "name_zh": "爱斯基摩犬",
        "name_en": "American Eskimo Dog",
        "origin": "美国（德国血统）",
        "size": "多种（玩具/迷你/标准）",
        "weight_range": "3-16 kg（视类型）",
        "height_range": "23-48 cm（视类型）",
        "lifespan": "13-15年",
        "personality": ["聪明", "活泼", "友善", "警觉"],
        "coat_color": ["纯白", "奶白"],
        "coat_length": "厚双层",
        "shedding": "高",
        "exercise_need": "中高",
        "feeding_tips": "视体型而定",
        "forbidden_foods": ["葡萄", "巧克力"],
        "recommended_food": "对应体型专用粮",
        "common_diseases": ["髌骨脱位（小型）", "渐进性视网膜萎缩", "白内障"],
        "vaccine_schedule": "标准程序接种",
        "grooming": "每周梳毛2-3次，每月洗澡",
        "tags": ["多种体型", "非运动犬", "中高活跃度", "纯白", "聪明"],
        "image_url": "",
        "description": "美国爱斯基摩犬（非真正的爱斯基摩犬）是聪明活泼的白色犬种，适合家庭生活。"
    },
    {
        "breed_id": "057",
        "name_zh": "沙皮犬",
        "name_en": "Shar Pei",
        "origin": "中国广东",
        "size": "中型犬",
        "weight_range": "18-29 kg",
        "height_range": "44-51 cm",
        "lifespan": "8-12年",
        "personality": ["忠诚", "冷静", "独立", "保护性强"],
        "coat_color": ["黑色", "棕色", "奶油色", "红色", "紫貂色"],
        "coat_length": "极短（马毛型/刷毛型/熊毛型）",
        "shedding": "低",
        "exercise_need": "中",
        "feeding_tips": "每日进食量约300-400g",
        "forbidden_foods": ["葡萄", "巧克力"],
        "recommended_food": "中型犬专用粮",
        "common_diseases": ["皮肤褶皱感染", "沙皮犬发热综合征（SPAID）", "眼睑内翻", "肾脏问题"],
        "vaccine_schedule": "标准程序接种",
        "grooming": "定期清洁皮肤褶皱，防止感染，每月洗澡",
        "tags": ["中型犬", "非运动犬", "中活跃度", "中国原产", "皱皮犬"],
        "image_url": "",
        "description": "沙皮犬是中国古老犬种，以其布满皱纹的皮肤著称，性格忠诚冷静，是独特的伴侣犬。"
    },
    {
        "breed_id": "058",
        "name_zh": "巴塞特猎犬",
        "name_en": "Basset Hound",
        "origin": "法国",
        "size": "中型犬",
        "weight_range": "18-27 kg",
        "height_range": "33-38 cm",
        "lifespan": "10-12年",
        "personality": ["温顺", "固执", "爱叫", "慵懒"],
        "coat_color": ["三色（黑棕白）", "柠檬白", "红白"],
        "coat_length": "短",
        "shedding": "中",
        "exercise_need": "低",
        "feeding_tips": "每日进食量约250-350g，易肥胖",
        "forbidden_foods": ["葡萄", "巧克力"],
        "recommended_food": "低卡路里控重犬粮",
        "common_diseases": ["椎间盘疾病", "肥胖", "耳道感染（长下垂耳）", "眼睑外翻"],
        "vaccine_schedule": "标准程序接种",
        "grooming": "每周梳毛，定期清耳，每月洗澡",
        "tags": ["中型犬", "猎犬", "低活跃度", "长耳短腿", "嗅觉猎犬"],
        "image_url": "",
        "description": "巴塞特猎犬以其超长的耳朵、哀怨的眼神和慵懒的性格著称，嗅觉极其灵敏。"
    },
    {
        "breed_id": "059",
        "name_zh": "寻血猎犬",
        "name_en": "Bloodhound",
        "origin": "比利时",
        "size": "大型犬",
        "weight_range": "36-50 kg",
        "height_range": "58-69 cm",
        "lifespan": "7-10年",
        "personality": ["温顺", "固执", "安静", "独立"],
        "coat_color": ["黑棕", "红棕", "红色"],
        "coat_length": "短",
        "shedding": "中",
        "exercise_need": "高",
        "feeding_tips": "每日进食量约500-600g",
        "forbidden_foods": ["葡萄", "巧克力"],
        "recommended_food": "大型犬专用粮",
        "common_diseases": ["耳道感染", "眼睑问题", "胃扭转", "髋关节问题"],
        "vaccine_schedule": "标准程序接种",
        "grooming": "每周梳毛，定期清耳，每月洗澡",
        "tags": ["大型犬", "猎犬", "高活跃度", "嗅觉之王", "追踪犬"],
        "image_url": "",
        "description": "寻血猎犬拥有世界上最灵敏的嗅觉，是最著名的追踪犬种，外表温顺友善。"
    },
    {
        "breed_id": "060",
        "name_zh": "爱尔兰赛特犬",
        "name_en": "Irish Setter",
        "origin": "爱尔兰",
        "size": "大型犬",
        "weight_range": "25-32 kg",
        "height_range": "58-68 cm",
        "lifespan": "12-15年",
        "personality": ["活泼热情", "友善", "开朗", "精力充沛"],
        "coat_color": ["红色", "红棕色"],
        "coat_length": "中长丝滑",
        "shedding": "中",
        "exercise_need": "极高",
        "feeding_tips": "每日进食量约400-500g",
        "forbidden_foods": ["葡萄", "巧克力"],
        "recommended_food": "大型运动犬高能量粮",
        "common_diseases": ["髋关节发育不良", "进行性视网膜萎缩", "癫痫", "乳糜泻"],
        "vaccine_schedule": "标准程序接种",
        "grooming": "每周梳毛2-3次，每月洗澡",
        "tags": ["大型犬", "运动犬", "极高活跃度", "红色猎犬", "美丽"],
        "image_url": "",
        "description": "爱尔兰赛特犬以其火红色的丝滑毛发著称，是最美丽的犬种之一，活泼热情。"
    },
    {
        "breed_id": "061",
        "name_zh": "吉娃娃",
        "name_en": "Chihuahua",
        "origin": "墨西哥",
        "size": "小型犬",
        "weight_range": "1-3 kg",
        "height_range": "15-23 cm",
        "lifespan": "12-20年",
        "personality": ["活泼好动", "忠诚黏人", "机警勇敢", "个性强烈"],
        "coat_color": ["浅棕色", "黑白", "纯棕", "奶油色"],
        "coat_length": "短毛/长毛",
        "shedding": "中等",
        "exercise_need": "低",
        "feeding_tips": "建议每日喂食2-3次，选用小型犬专用粮，注意控制零食量避免肥胖",
        "forbidden_foods": ["巧克力", "葡萄", "洋葱", "大蒜", "木糖醇"],
        "recommended_food": "优质小型犬粮，可搭配适量鸡胸肉和蔬菜",
        "common_diseases": ["髌骨脱位", "牙齿问题", "气管塌陷", "脑积水", "低血糖"],
        "vaccine_schedule": "幼犬6-8周首免，之后每3-4周加强一次，成年后每年加强",
        "grooming": "短毛每周梳毛1-2次，长毛每天梳毛，定期修剪指甲和清洁耳朵",
        "tags": ["小型犬", "玩具犬", "陪伴犬"],
        "image_url": "",
        "description": "吉娃娃是世界上体型最小的犬种之一，以巨大的性格和忠诚度著称，是优秀的城市伴侣犬。"
    },
    {
        "breed_id": "062",
        "name_zh": "日本狆",
        "name_en": "Japanese Chin",
        "origin": "日本",
        "size": "小型犬",
        "weight_range": "2-5 kg",
        "height_range": "20-27 cm",
        "lifespan": "12-14年",
        "personality": ["优雅安静", "聪明机敏", "温柔亲人"],
        "coat_color": ["黑白", "红白"],
        "coat_length": "长毛",
        "shedding": "中等",
        "exercise_need": "低",
        "feeding_tips": "每日喂食2次，选用小型犬粮，注意口腔卫生",
        "forbidden_foods": ["巧克力", "葡萄", "洋葱", "大蒜", "木糖醇"],
        "recommended_food": "小型犬专用粮，可添加益生菌促进消化",
        "common_diseases": ["心脏问题", "眼部疾病", "髌骨脱位", "呼吸道问题"],
        "vaccine_schedule": "幼犬6-8周首免，之后每3-4周加强一次",
        "grooming": "每周梳毛3-4次，定期清洁眼部",
        "tags": ["小型犬", "玩具犬", "优雅"],
        "image_url": "",
        "description": "日本狆是一种优雅的小型犬，性格温顺安静，适合公寓生活，是理想的伴侣犬。"
    },
    {
        "breed_id": "063",
        "name_zh": "北京犬",
        "name_en": "Pekinese",
        "origin": "中国",
        "size": "小型犬",
        "weight_range": "3-6 kg",
        "height_range": "15-23 cm",
        "lifespan": "12-15年",
        "personality": ["自信独立", "忠诚护主", "高贵冷静"],
        "coat_color": ["金色", "红色", "黑色", "奶油色"],
        "coat_length": "长毛",
        "shedding": "高",
        "exercise_need": "低",
        "feeding_tips": "每日喂食2次，注意控制体重，避免过度肥胖",
        "forbidden_foods": ["巧克力", "葡萄", "洋葱", "大蒜"],
        "recommended_food": "优质犬粮搭配适量肉类",
        "common_diseases": ["呼吸道问题", "眼疾", "脊柱问题", "心脏病"],
        "vaccine_schedule": "标准接种程序",
        "grooming": "每日梳毛，定期修剪面部毛发",
        "tags": ["小型犬", "玩具犬", "中国犬"],
        "image_url": "",
        "description": "北京犬是中国古老的宫廷犬种，个性独立高贵，对主人极为忠诚。"
    },
    {
        "breed_id": "064",
        "name_zh": "西施犬",
        "name_en": "Shih Tzu",
        "origin": "中国",
        "size": "小型犬",
        "weight_range": "4-7 kg",
        "height_range": "20-28 cm",
        "lifespan": "10-16年",
        "personality": ["活泼开朗", "友善亲人", "温柔可爱"],
        "coat_color": ["金色", "黑白", "棕白", "纯色"],
        "coat_length": "长毛",
        "shedding": "低",
        "exercise_need": "低",
        "feeding_tips": "每日喂食2-3次，选用优质小型犬粮",
        "forbidden_foods": ["巧克力", "葡萄", "洋葱"],
        "recommended_food": "小型犬专用粮",
        "common_diseases": ["眼疾", "呼吸道问题", "皮肤过敏", "牙齿问题"],
        "vaccine_schedule": "标准接种程序",
        "grooming": "每日梳毛，定期修剪，保持面部清洁",
        "tags": ["小型犬", "伴侣犬", "长毛犬"],
        "image_url": "",
        "description": "西施犬是中国传统犬种，性格开朗友善，是优秀的家庭伴侣犬。"
    },
    {
        "breed_id": "065",
        "name_zh": "骑士查理王小猎犬",
        "name_en": "Cavalier King Charles Spaniel",
        "origin": "英国",
        "size": "小型犬",
        "weight_range": "5-8 kg",
        "height_range": "30-33 cm",
        "lifespan": "9-14年",
        "personality": ["温柔友善", "活泼亲人", "安静温和"],
        "coat_color": ["红棕色", "黑棕", "三色"],
        "coat_length": "中长丝滑",
        "shedding": "中等",
        "exercise_need": "中等",
        "feeding_tips": "每日喂食2次，适量运动",
        "forbidden_foods": ["巧克力", "葡萄"],
        "recommended_food": "小型犬粮",
        "common_diseases": ["二尖瓣心脏病", "脊髓空洞症", "眼疾", "耳部感染"],
        "vaccine_schedule": "标准接种程序",
        "grooming": "每周梳毛3-4次，定期清洁耳朵",
        "tags": ["小型犬", "伴侣犬", "猎鹬犬"],
        "image_url": "",
        "description": "骑士查理王小猎犬是英国王室最爱的犬种之一，性格温柔亲人，被称为\"""治愈系伴侣犬\"""。"
    },
    {
        "breed_id": "066",
        "name_zh": "蝴蝶犬",
        "name_en": "Papillon",
        "origin": "法国/比利时",
        "size": "小型犬",
        "weight_range": "3-5 kg",
        "height_range": "20-28 cm",
        "lifespan": "13-15年",
        "personality": ["聪明机灵", "活泼好动", "亲人友善"],
        "coat_color": ["白色带斑点", "黑棕白"],
        "coat_length": "长毛",
        "shedding": "中等",
        "exercise_need": "中等",
        "feeding_tips": "每日2次少量喂食，保持适度运动",
        "forbidden_foods": ["巧克力", "葡萄"],
        "recommended_food": "小型犬粮",
        "common_diseases": ["髌骨脱位", "牙齿问题", "进行性视网膜萎缩"],
        "vaccine_schedule": "标准接种程序",
        "grooming": "每周梳毛2-3次",
        "tags": ["小型犬", "玩具犬", "聪明"],
        "image_url": "",
        "description": "蝴蝶犬因耳朵像蝴蝶翅膀而得名，是最聪明的小型犬之一，在犬类智力排名中位列前列。"
    },
    {
        "breed_id": "067",
        "name_zh": "玩具梗犬",
        "name_en": "Toy Terrier",
        "origin": "英国",
        "size": "小型犬",
        "weight_range": "2-4 kg",
        "height_range": "22-28 cm",
        "lifespan": "12-15年",
        "personality": ["活泼机敏", "勇敢自信", "精力充沛"],
        "coat_color": ["黑棕", "纯黑"],
        "coat_length": "短毛",
        "shedding": "低",
        "exercise_need": "中等",
        "feeding_tips": "少量多餐，注意钙质补充",
        "forbidden_foods": ["巧克力", "葡萄"],
        "recommended_food": "小型犬高能量粮",
        "common_diseases": ["髌骨脱位", "牙齿问题", "皮肤过敏"],
        "vaccine_schedule": "标准接种程序",
        "grooming": "每周梳毛1-2次",
        "tags": ["小型犬", "梗犬", "活泼"],
        "image_url": "",
        "description": "玩具梗犬体型娇小但性格勇敢，是典型的\"""小身体大能量\"""犬种。"
    },
    {
        "breed_id": "068",
        "name_zh": "罗德西亚脊背犬",
        "name_en": "Rhodesian Ridgeback",
        "origin": "南非",
        "size": "大型犬",
        "weight_range": "30-39 kg",
        "height_range": "61-69 cm",
        "lifespan": "10-12年",
        "personality": ["忠诚护主", "独立冷静", "勇敢无畏"],
        "coat_color": ["浅麦色", "红麦色"],
        "coat_length": "短毛",
        "shedding": "中等",
        "exercise_need": "高",
        "feeding_tips": "每日喂食2次，高蛋白犬粮",
        "forbidden_foods": ["巧克力", "葡萄", "高盐食物"],
        "recommended_food": "大型运动犬粮",
        "common_diseases": ["髋关节发育不良", "皮样窦", "甲状腺功能减退"],
        "vaccine_schedule": "标准接种程序",
        "grooming": "每周梳毛1-2次",
        "tags": ["大型犬", "猎犬", "护卫犬"],
        "image_url": "",
        "description": "罗德西亚脊背犬原产于南非，因背部独特的逆毛脊线而得名，曾被用于狩猎狮子。"
    },
    {
        "breed_id": "069",
        "name_zh": "阿富汗猎犬",
        "name_en": "Afghan Hound",
        "origin": "阿富汗",
        "size": "大型犬",
        "weight_range": "23-27 kg",
        "height_range": "64-74 cm",
        "lifespan": "12-14年",
        "personality": ["优雅高贵", "独立自主", "忠诚专一"],
        "coat_color": ["金色", "银色", "黑色", "奶油色"],
        "coat_length": "长丝滑",
        "shedding": "低",
        "exercise_need": "高",
        "feeding_tips": "每日喂食2次，高蛋白优质犬粮",
        "forbidden_foods": ["巧克力", "葡萄"],
        "recommended_food": "大型犬高能量粮",
        "common_diseases": ["髋关节发育不良", "白内障", "甲状腺功能减退"],
        "vaccine_schedule": "标准接种程序",
        "grooming": "每日梳毛，定期洗澡和修剪",
        "tags": ["大型犬", "猎犬", "优雅", "长毛"],
        "image_url": "",
        "description": "阿富汗猎犬是世界上最高贵的犬种之一，以其丝滑飘逸的长发和优雅气质闻名于世。"
    },
    {
        "breed_id": "070",
        "name_zh": "蓝斑猎浣熊犬",
        "name_en": "Bluetick Coonhound",
        "origin": "美国",
        "size": "大型犬",
        "weight_range": "20-36 kg",
        "height_range": "53-69 cm",
        "lifespan": "11-12年",
        "personality": ["友善温和", "聪明独立", "嗅觉灵敏"],
        "coat_color": ["蓝斑色", "黑斑白底"],
        "coat_length": "短毛",
        "shedding": "中等",
        "exercise_need": "高",
        "feeding_tips": "每日喂食2次，高蛋白粮，注意运动量",
        "forbidden_foods": ["巧克力", "葡萄"],
        "recommended_food": "大型运动犬粮",
        "common_diseases": ["髋关节发育不良", "耳部感染", "腹胀"],
        "vaccine_schedule": "标准接种程序",
        "grooming": "每周梳毛1-2次，定期清洁耳朵",
        "tags": ["大型犬", "猎犬", "嗅觉"],
        "image_url": "",
        "description": "蓝斑猎浣熊犬以其独特的蓝斑色被毛和出色的嗅觉追踪能力著称。"
    },
    {
        "breed_id": "071",
        "name_zh": "黑棕猎浣熊犬",
        "name_en": "Black and Tan Coonhound",
        "origin": "美国",
        "size": "大型犬",
        "weight_range": "23-34 kg",
        "height_range": "58-69 cm",
        "lifespan": "10-12年",
        "personality": ["温和友善", "忠诚可靠", "工作热情"],
        "coat_color": ["黑棕"],
        "coat_length": "短毛",
        "shedding": "中等",
        "exercise_need": "高",
        "feeding_tips": "每日喂食2次，高能量犬粮",
        "forbidden_foods": ["巧克力", "葡萄"],
        "recommended_food": "大型犬高能量粮",
        "common_diseases": ["髋关节发育不良", "耳部感染", "眼部疾病"],
        "vaccine_schedule": "标准接种程序",
        "grooming": "每周梳毛1-2次",
        "tags": ["大型犬", "猎犬"],
        "image_url": "",
        "description": "黑棕猎浣熊犬是美国培育的猎犬品种，主要以其出色的夜间追踪能力闻名。"
    },
    {
        "breed_id": "072",
        "name_zh": "沃克猎犬",
        "name_en": "Treeing Walker Coonhound",
        "origin": "美国",
        "size": "大型犬",
        "weight_range": "20-32 kg",
        "height_range": "51-69 cm",
        "lifespan": "12-13年",
        "personality": ["活泼热情", "聪明敏锐", "友善亲人"],
        "coat_color": ["白黑棕三色"],
        "coat_length": "短毛",
        "shedding": "中等",
        "exercise_need": "极高",
        "feeding_tips": "每日2-3次高能量粮，充足运动",
        "forbidden_foods": ["巧克力", "葡萄"],
        "recommended_food": "运动犬高蛋白粮",
        "common_diseases": ["髋关节发育不良", "耳部感染"],
        "vaccine_schedule": "标准接种程序",
        "grooming": "每周梳毛1-2次",
        "tags": ["大型犬", "猎犬", "高能量"],
        "image_url": "",
        "description": "沃克猎犬是美国最受欢迎的猎浣熊犬品种之一，以速度和耐力著称。"
    },
    {
        "breed_id": "073",
        "name_zh": "英国猎狐犬",
        "name_en": "English Foxhound",
        "origin": "英国",
        "size": "大型犬",
        "weight_range": "25-34 kg",
        "height_range": "58-64 cm",
        "lifespan": "10-13年",
        "personality": ["温和友善", "群居性强", "耐力出众"],
        "coat_color": ["黑棕白三色"],
        "coat_length": "短毛",
        "shedding": "中等",
        "exercise_need": "极高",
        "feeding_tips": "每日2次，高能量粮",
        "forbidden_foods": ["巧克力"],
        "recommended_food": "大型运动犬粮",
        "common_diseases": ["髋关节发育不良", "肾脏疾病", "耳部感染"],
        "vaccine_schedule": "标准接种程序",
        "grooming": "每周梳毛1-2次",
        "tags": ["大型犬", "猎犬", "群居"],
        "image_url": "",
        "description": "英国猎狐犬是传统猎狐用犬，以其卓越的嗅觉和耐力在狩猎中表现出色。"
    },
    {
        "breed_id": "074",
        "name_zh": "红骨猎浣熊犬",
        "name_en": "Redbone Coonhound",
        "origin": "美国",
        "size": "大型犬",
        "weight_range": "20-32 kg",
        "height_range": "53-69 cm",
        "lifespan": "12-14年",
        "personality": ["温和友善", "忠诚可靠", "精力充沛"],
        "coat_color": ["红棕色"],
        "coat_length": "短毛",
        "shedding": "中等",
        "exercise_need": "高",
        "feeding_tips": "每日2次高蛋白粮",
        "forbidden_foods": ["巧克力", "葡萄"],
        "recommended_food": "大型犬粮",
        "common_diseases": ["髋关节发育不良", "耳部感染"],
        "vaccine_schedule": "标准接种程序",
        "grooming": "每周梳毛1-2次",
        "tags": ["大型犬", "猎犬", "红毛"],
        "image_url": "",
        "description": "红骨猎浣熊犬以美丽的红棕色被毛和友善的性格著称，是优秀的家庭伙伴。"
    },
    {
        "breed_id": "075",
        "name_zh": "苏俄猎狼犬",
        "name_en": "Borzoi",
        "origin": "俄罗斯",
        "size": "超大型犬",
        "weight_range": "27-48 kg",
        "height_range": "68-85 cm",
        "lifespan": "7-10年",
        "personality": ["优雅安静", "独立冷静", "忠诚温和"],
        "coat_color": ["白色", "金色", "灰色", "虎斑"],
        "coat_length": "长丝滑",
        "shedding": "高",
        "exercise_need": "高",
        "feeding_tips": "每日喂食2次，注意关节保健",
        "forbidden_foods": ["巧克力", "葡萄", "高盐食物"],
        "recommended_food": "大型犬专用粮，添加关节补充剂",
        "common_diseases": ["胃扭转", "髋关节发育不良", "心脏病", "进行性视网膜萎缩"],
        "vaccine_schedule": "标准接种，注意麻醉敏感性",
        "grooming": "每周梳毛3-4次，定期洗澡",
        "tags": ["超大型犬", "猎犬", "优雅", "长毛"],
        "image_url": "",
        "description": "苏俄猎狼犬是俄罗斯贵族的猎犬，以极速奔跑和优雅外形闻名。"
    },
    {
        "breed_id": "076",
        "name_zh": "惠比特犬",
        "name_en": "Whippet",
        "origin": "英国",
        "size": "中型犬",
        "weight_range": "9-19 kg",
        "height_range": "44-56 cm",
        "lifespan": "12-15年",
        "personality": ["温柔安静", "敏捷迅速", "亲人黏人"],
        "coat_color": ["各色纯色或斑点"],
        "coat_length": "短毛",
        "shedding": "低",
        "exercise_need": "中高",
        "feeding_tips": "每日喂食2次，注意保暖",
        "forbidden_foods": ["巧克力", "葡萄"],
        "recommended_food": "中型运动犬粮",
        "common_diseases": ["麻醉敏感", "皮肤划伤", "心脏病"],
        "vaccine_schedule": "标准接种，注意麻醉敏感性",
        "grooming": "每周梳毛1次",
        "tags": ["中型犬", "赛犬", "优雅"],
        "image_url": "",
        "description": "惠比特犬被称为\"""穷人的赛马\"""，是世界上加速最快的犬种之一。"
    },
    {
        "breed_id": "077",
        "name_zh": "伊比赞猎犬",
        "name_en": "Ibizan Hound",
        "origin": "西班牙",
        "size": "大型犬",
        "weight_range": "20-29 kg",
        "height_range": "56-74 cm",
        "lifespan": "11-14年",
        "personality": ["优雅活泼", "独立聪明", "友善亲人"],
        "coat_color": ["白色", "红色", "红白"],
        "coat_length": "短毛/刚毛",
        "shedding": "低",
        "exercise_need": "高",
        "feeding_tips": "每日2次优质犬粮",
        "forbidden_foods": ["巧克力", "葡萄"],
        "recommended_food": "大型运动犬粮",
        "common_diseases": ["麻醉敏感", "髋关节发育不良", "耳聋"],
        "vaccine_schedule": "标准接种程序",
        "grooming": "短毛每周1次，刚毛每周2-3次",
        "tags": ["大型犬", "猎犬", "古老犬种"],
        "image_url": "",
        "description": "伊比赞猎犬是源自西班牙的古老犬种，形似埃及壁画中的犬只，以惊人的弹跳力著称。"
    },
    {
        "breed_id": "078",
        "name_zh": "挪威猎麋犬",
        "name_en": "Norwegian Elkhound",
        "origin": "挪威",
        "size": "中型犬",
        "weight_range": "20-25 kg",
        "height_range": "46-52 cm",
        "lifespan": "12-15年",
        "personality": ["勇敢忠诚", "友善温和", "独立自信"],
        "coat_color": ["灰色"],
        "coat_length": "中等双层",
        "shedding": "高",
        "exercise_need": "高",
        "feeding_tips": "每日2次，控制体重",
        "forbidden_foods": ["巧克力", "葡萄"],
        "recommended_food": "中型犬粮",
        "common_diseases": ["髋关节发育不良", "进行性视网膜萎缩", "甲状腺功能减退"],
        "vaccine_schedule": "标准接种程序",
        "grooming": "每周梳毛2-3次，换毛季每天",
        "tags": ["中型犬", "猎犬", "北欧"],
        "image_url": "",
        "description": "挪威猎麋犬是挪威的国犬，维京人时代的古老犬种，以狩猎麋鹿而闻名。"
    },
    {
        "breed_id": "079",
        "name_zh": "水獭猎犬",
        "name_en": "Otterhound",
        "origin": "英国",
        "size": "大型犬",
        "weight_range": "30-52 kg",
        "height_range": "61-69 cm",
        "lifespan": "10-13年",
        "personality": ["友善开朗", "温和亲人", "独立固执"],
        "coat_color": ["各色组合"],
        "coat_length": "中长粗糙",
        "shedding": "低",
        "exercise_need": "高",
        "feeding_tips": "每日2次，注意关节",
        "forbidden_foods": ["巧克力", "高盐食物"],
        "recommended_food": "大型犬粮",
        "common_diseases": ["髋关节发育不良", "胃扭转", "癫痫"],
        "vaccine_schedule": "标准接种程序",
        "grooming": "每周梳毛2-3次",
        "tags": ["大型犬", "猎犬", "稀有"],
        "image_url": "",
        "description": "水獭猎犬是世界上最稀有的犬种之一，有蹼足和防水被毛，专门用于水中狩猎。"
    },
    {
        "breed_id": "080",
        "name_zh": "苏格兰猎鹿犬",
        "name_en": "Scottish Deerhound",
        "origin": "英国苏格兰",
        "size": "超大型犬",
        "weight_range": "34-50 kg",
        "height_range": "71-81 cm",
        "lifespan": "8-11年",
        "personality": ["温柔巨人", "安静沉稳", "忠诚友善"],
        "coat_color": ["灰蓝色", "灰色", "斑纹"],
        "coat_length": "粗糙中长",
        "shedding": "中等",
        "exercise_need": "中高",
        "feeding_tips": "每日2次大型犬粮，关节护理",
        "forbidden_foods": ["巧克力", "葡萄"],
        "recommended_food": "超大型犬专用粮+关节保健品",
        "common_diseases": ["胃扭转", "骨肉瘤", "心脏病", "髋关节发育不良"],
        "vaccine_schedule": "标准接种，注意麻醉风险",
        "grooming": "每周梳毛2-3次",
        "tags": ["超大型犬", "猎犬", "皇室犬"],
        "image_url": "",
        "description": "苏格兰猎鹿犬被称为\"""皇家苏格兰之犬\"""，体型高大优雅，是温和的巨人。"
    },
    {
        "breed_id": "081",
        "name_zh": "斯塔福郡斗牛梗",
        "name_en": "Staffordshire Bull Terrier",
        "origin": "英国",
        "size": "中型犬",
        "weight_range": "11-17 kg",
        "height_range": "35-41 cm",
        "lifespan": "12-14年",
        "personality": ["勇敢忠诚", "活泼亲人", "坚韧顽强"],
        "coat_color": ["红色", "白色", "黑色", "蓝色", "斑纹"],
        "coat_length": "短毛",
        "shedding": "低",
        "exercise_need": "中高",
        "feeding_tips": "每日2次，控制体重",
        "forbidden_foods": ["巧克力", "葡萄"],
        "recommended_food": "中型犬高蛋白粮",
        "common_diseases": ["髋关节发育不良", "白内障", "皮肤过敏"],
        "vaccine_schedule": "标准接种程序",
        "grooming": "每周梳毛1-2次",
        "tags": ["中型犬", "梗犬", "家庭犬"],
        "image_url": "",
        "description": "斯塔福郡斗牛梗被称为\"""保姆犬\"""，对儿童极为友善，是忠诚的家庭伴侣。"
    },
    {
        "breed_id": "082",
        "name_zh": "美国斯塔福郡梗",
        "name_en": "American Staffordshire Terrier",
        "origin": "美国",
        "size": "中型犬",
        "weight_range": "18-30 kg",
        "height_range": "43-48 cm",
        "lifespan": "12-16年",
        "personality": ["忠诚护主", "勇敢自信", "聪明友善"],
        "coat_color": ["各纯色或斑纹"],
        "coat_length": "短毛",
        "shedding": "低",
        "exercise_need": "高",
        "feeding_tips": "每日2次高蛋白粮",
        "forbidden_foods": ["巧克力", "葡萄"],
        "recommended_food": "高蛋白运动犬粮",
        "common_diseases": ["髋关节发育不良", "心脏病", "皮肤过敏"],
        "vaccine_schedule": "标准接种程序",
        "grooming": "每周梳毛1次",
        "tags": ["中型犬", "护卫犬", "力量型"],
        "image_url": "",
        "description": "美国斯塔福郡梗肌肉发达、外形威武，但对主人极其忠诚温和。"
    },
    {
        "breed_id": "083",
        "name_zh": "贝灵顿梗",
        "name_en": "Bedlington Terrier",
        "origin": "英国",
        "size": "小型犬",
        "weight_range": "8-10 kg",
        "height_range": "38-43 cm",
        "lifespan": "12-16年",
        "personality": ["活泼机敏", "温柔亲人", "勇敢好斗"],
        "coat_color": ["蓝色", "肝色", "沙色"],
        "coat_length": "卷曲羊毛状",
        "shedding": "极低",
        "exercise_need": "中等",
        "feeding_tips": "每日2次，注意皮肤健康",
        "forbidden_foods": ["巧克力", "高脂食物"],
        "recommended_food": "小型犬粮",
        "common_diseases": ["铜中毒症", "视网膜疾病", "肾脏疾病"],
        "vaccine_schedule": "标准接种程序",
        "grooming": "需专业修剪，每6-8周一次",
        "tags": ["小型犬", "梗犬", "低敏"],
        "image_url": "",
        "description": "贝灵顿梗外形似小羊羔，是世界上最低敏的犬种之一，不掉毛。"
    },
    {
        "breed_id": "084",
        "name_zh": "边境梗",
        "name_en": "Border Terrier",
        "origin": "英国",
        "size": "小型犬",
        "weight_range": "5-7 kg",
        "height_range": "28-33 cm",
        "lifespan": "12-15年",
        "personality": ["活泼友善", "温和亲人", "勇敢机敏"],
        "coat_color": ["红色", "灰色", "棕褐色"],
        "coat_length": "短刚毛",
        "shedding": "低",
        "exercise_need": "中等",
        "feeding_tips": "每日2次",
        "forbidden_foods": ["巧克力"],
        "recommended_food": "小型犬粮",
        "common_diseases": ["髋关节发育不良", "白内障", "心脏病"],
        "vaccine_schedule": "标准接种程序",
        "grooming": "每周手拔毛或梳毛",
        "tags": ["小型犬", "梗犬", "家庭犬"],
        "image_url": "",
        "description": "边境梗是温和的梗犬品种，性格柔顺亲人，是非常适合家庭的伴侣犬。"
    },
    {
        "breed_id": "085",
        "name_zh": "爱尔兰梗",
        "name_en": "Irish Terrier",
        "origin": "爱尔兰",
        "size": "中型犬",
        "weight_range": "11-12 kg",
        "height_range": "46-48 cm",
        "lifespan": "13-15年",
        "personality": ["勇敢无畏", "忠诚热情", "活泼机警"],
        "coat_color": ["红色", "红麦色"],
        "coat_length": "刚毛",
        "shedding": "低",
        "exercise_need": "高",
        "feeding_tips": "每日2次",
        "forbidden_foods": ["巧克力"],
        "recommended_food": "中型犬高能量粮",
        "common_diseases": ["膀胱结石", "甲状腺功能减退"],
        "vaccine_schedule": "标准接种程序",
        "grooming": "定期手拔毛保持毛质",
        "tags": ["中型犬", "梗犬", "爱尔兰"],
        "image_url": "",
        "description": "爱尔兰梗被称为\"""红色魔鬼\"""，因其火红被毛和无所畏惧的性格而得名。"
    },
    {
        "breed_id": "086",
        "name_zh": "诺福克梗",
        "name_en": "Norfolk Terrier",
        "origin": "英国",
        "size": "小型犬",
        "weight_range": "5-6 kg",
        "height_range": "23-25 cm",
        "lifespan": "12-16年",
        "personality": ["活泼开朗", "自信勇敢", "友善亲人"],
        "coat_color": ["红色", "黑色", "棕褐"],
        "coat_length": "刚毛",
        "shedding": "低",
        "exercise_need": "中等",
        "feeding_tips": "每日2次",
        "forbidden_foods": ["巧克力"],
        "recommended_food": "小型犬粮",
        "common_diseases": ["髌骨脱位", "心脏病"],
        "vaccine_schedule": "标准接种程序",
        "grooming": "定期手拔毛",
        "tags": ["小型犬", "梗犬"],
        "image_url": "",
        "description": "诺福克梗是英国最小的梗犬之一，垂耳是区分诺里奇梗的主要特征。"
    },
    {
        "breed_id": "087",
        "name_zh": "诺里奇梗",
        "name_en": "Norwich Terrier",
        "origin": "英国",
        "size": "小型犬",
        "weight_range": "4-6 kg",
        "height_range": "23-25 cm",
        "lifespan": "12-15年",
        "personality": ["活泼好动", "勇敢自信", "亲人友善"],
        "coat_color": ["红色", "黑色", "棕褐"],
        "coat_length": "刚毛",
        "shedding": "低",
        "exercise_need": "中等",
        "feeding_tips": "每日2次",
        "forbidden_foods": ["巧克力"],
        "recommended_food": "小型犬粮",
        "common_diseases": ["气管塌陷", "癫痫", "髋关节发育不良"],
        "vaccine_schedule": "标准接种程序",
        "grooming": "定期手拔毛",
        "tags": ["小型犬", "梗犬"],
        "image_url": "",
        "description": "诺里奇梗体型小但胆量大，立耳是与诺福克梗的主要区别特征。"
    },
    {
        "breed_id": "088",
        "name_zh": "湖畔梗",
        "name_en": "Lakeland Terrier",
        "origin": "英国",
        "size": "小型犬",
        "weight_range": "7-8 kg",
        "height_range": "33-38 cm",
        "lifespan": "12-16年",
        "personality": ["活泼自信", "勇敢机敏", "聪明好学"],
        "coat_color": ["各色"],
        "coat_length": "刚毛",
        "shedding": "低",
        "exercise_need": "中等",
        "feeding_tips": "每日2次",
        "forbidden_foods": ["巧克力"],
        "recommended_food": "小型犬粮",
        "common_diseases": ["白内障", "青光眼"],
        "vaccine_schedule": "标准接种程序",
        "grooming": "定期手拔毛",
        "tags": ["小型犬", "梗犬"],
        "image_url": "",
        "description": "湖畔梗原产于英国湖区，用于猎狐，是活泼勇敢的工作犬。"
    },
    {
        "breed_id": "089",
        "name_zh": "西里汉梗",
        "name_en": "Sealyham Terrier",
        "origin": "英国威尔士",
        "size": "小型犬",
        "weight_range": "8-11 kg",
        "height_range": "27-31 cm",
        "lifespan": "12-14年",
        "personality": ["温和安静", "忠诚勇敢", "独立固执"],
        "coat_color": ["白色带斑纹"],
        "coat_length": "中长刚毛",
        "shedding": "低",
        "exercise_need": "中等",
        "feeding_tips": "每日2次",
        "forbidden_foods": ["巧克力"],
        "recommended_food": "小型犬粮",
        "common_diseases": ["视网膜退化", "过敏"],
        "vaccine_schedule": "标准接种程序",
        "grooming": "定期修剪和手拔毛",
        "tags": ["小型犬", "梗犬", "稀有"],
        "image_url": "",
        "description": "西里汉梗曾是英国最受欢迎的犬种之一，以独特的白色被毛和长眉毛著称。"
    },
    {
        "breed_id": "090",
        "name_zh": "万能梗",
        "name_en": "Airedale Terrier",
        "origin": "英国",
        "size": "大型犬",
        "weight_range": "18-29 kg",
        "height_range": "56-61 cm",
        "lifespan": "10-13年",
        "personality": ["聪明勇敢", "忠诚友善", "多才多艺"],
        "coat_color": ["黑棕"],
        "coat_length": "刚毛",
        "shedding": "低",
        "exercise_need": "高",
        "feeding_tips": "每日2次，高蛋白粮",
        "forbidden_foods": ["巧克力"],
        "recommended_food": "大型运动犬粮",
        "common_diseases": ["髋关节发育不良", "皮肤问题"],
        "vaccine_schedule": "标准接种程序",
        "grooming": "定期手拔毛或修剪",
        "tags": ["大型犬", "梗犬之王"],
        "image_url": "",
        "description": "万能梗被称为\"""梗犬之王\"""，是体型最大的梗犬，曾在战争中服役。"
    },
    {
        "breed_id": "091",
        "name_zh": "澳大利亚梗",
        "name_en": "Australian Terrier",
        "origin": "澳大利亚",
        "size": "小型犬",
        "weight_range": "4-6 kg",
        "height_range": "23-28 cm",
        "lifespan": "12-15年",
        "personality": ["活泼机敏", "勇敢自信", "忠诚警觉"],
        "coat_color": ["蓝棕", "红沙色"],
        "coat_length": "中长刚毛",
        "shedding": "低",
        "exercise_need": "中等",
        "feeding_tips": "每日2次",
        "forbidden_foods": ["巧克力"],
        "recommended_food": "小型犬粮",
        "common_diseases": ["髌骨脱位", "糖尿病", "皮肤过敏"],
        "vaccine_schedule": "标准接种程序",
        "grooming": "每周梳毛2-3次",
        "tags": ["小型犬", "梗犬"],
        "image_url": "",
        "description": "澳大利亚梗是澳洲培育的第一个犬种，是坚韧的工作犬和亲密的伴侣犬。"
    },
    {
        "breed_id": "092",
        "name_zh": "丹迪丁蒙梗",
        "name_en": "Dandie Dinmont Terrier",
        "origin": "英国苏格兰",
        "size": "小型犬",
        "weight_range": "8-11 kg",
        "height_range": "20-28 cm",
        "lifespan": "12-15年",
        "personality": ["独立冷静", "忠诚温和", "聪明机敏"],
        "coat_color": ["胡椒色", "芥末色"],
        "coat_length": "中长柔软",
        "shedding": "极低",
        "exercise_need": "中低",
        "feeding_tips": "每日2次，注意控制体重",
        "forbidden_foods": ["巧克力"],
        "recommended_food": "小型犬粮",
        "common_diseases": ["椎间盘疾病", "青光眼", "甲状腺功能减退"],
        "vaccine_schedule": "标准接种程序",
        "grooming": "每周梳毛2-3次，定期修剪",
        "tags": ["小型犬", "梗犬", "稀有"],
        "image_url": "",
        "description": "丹迪丁蒙梗以其独特的\"""头饰\"""和大眼睛闻名，是小说角色命名而来的犬种。"
    },
    {
        "breed_id": "093",
        "name_zh": "波士顿梗",
        "name_en": "Boston Terrier",
        "origin": "美国",
        "size": "小型犬",
        "weight_range": "5-11 kg",
        "height_range": "38-43 cm",
        "lifespan": "11-13年",
        "personality": ["活泼友善", "聪明可爱", "温和亲人"],
        "coat_color": ["黑白相间", "虎斑白"],
        "coat_length": "短毛",
        "shedding": "低",
        "exercise_need": "中等",
        "feeding_tips": "每日2次，注意呼吸问题",
        "forbidden_foods": ["巧克力"],
        "recommended_food": "小型犬粮",
        "common_diseases": ["呼吸道问题", "眼疾", "髌骨脱位", "耳聋"],
        "vaccine_schedule": "标准接种程序",
        "grooming": "每周梳毛1次",
        "tags": ["小型犬", "美国绅士"],
        "image_url": "",
        "description": "波士顿梗被称为\"""美国绅士\"""，因其燕尾服般的黑白配色和优雅气质得名。"
    },
    {
        "breed_id": "094",
        "name_zh": "巨型雪纳瑞",
        "name_en": "Giant Schnauzer",
        "origin": "德国",
        "size": "大型犬",
        "weight_range": "25-47 kg",
        "height_range": "60-70 cm",
        "lifespan": "12-15年",
        "personality": ["忠诚护主", "聪明勇敢", "威严可靠"],
        "coat_color": ["黑色", "椒盐色"],
        "coat_length": "刚毛",
        "shedding": "低",
        "exercise_need": "高",
        "feeding_tips": "每日2次，高蛋白粮",
        "forbidden_foods": ["巧克力", "高盐食物"],
        "recommended_food": "大型犬高能量粮",
        "common_diseases": ["髋关节发育不良", "甲状腺功能减退", "胃癌"],
        "vaccine_schedule": "标准接种程序",
        "grooming": "定期修剪和梳理",
        "tags": ["大型犬", "工作犬", "护卫犬"],
        "image_url": "",
        "description": "巨型雪纳瑞是雪纳瑞家族中体型最大的一员，常用于警犬和护卫工作。"
    },
    {
        "breed_id": "095",
        "name_zh": "标准雪纳瑞",
        "name_en": "Standard Schnauzer",
        "origin": "德国",
        "size": "中型犬",
        "weight_range": "14-23 kg",
        "height_range": "44-50 cm",
        "lifespan": "13-16年",
        "personality": ["聪明机警", "忠诚友善", "活泼自信"],
        "coat_color": ["椒盐色", "纯黑"],
        "coat_length": "刚毛",
        "shedding": "极低",
        "exercise_need": "中高",
        "feeding_tips": "每日2次",
        "forbidden_foods": ["巧克力"],
        "recommended_food": "中型犬粮",
        "common_diseases": ["髋关节发育不良", "胰腺炎", "过敏"],
        "vaccine_schedule": "标准接种程序",
        "grooming": "每6-8周修剪一次",
        "tags": ["中型犬", "工作犬"],
        "image_url": "",
        "description": "标准雪纳瑞是雪纳瑞家族的原型品种，兼具智慧、勇气和亲和力。"
    },
    {
        "breed_id": "096",
        "name_zh": "苏格兰梗",
        "name_en": "Scottish Terrier",
        "origin": "英国苏格兰",
        "size": "小型犬",
        "weight_range": "8-10 kg",
        "height_range": "25-28 cm",
        "lifespan": "12-15年",
        "personality": ["独立自信", "忠诚护主", "威严冷静"],
        "coat_color": ["黑色", "小麦色", "斑纹"],
        "coat_length": "刚毛",
        "shedding": "极低",
        "exercise_need": "中等",
        "feeding_tips": "每日2次",
        "forbidden_foods": ["巧克力"],
        "recommended_food": "小型犬粮",
        "common_diseases": ["苏格兰梗痉挛症", "膀胱癌", "过敏"],
        "vaccine_schedule": "标准接种程序",
        "grooming": "定期修剪和手拔毛",
        "tags": ["小型犬", "梗犬", "经典"],
        "image_url": "",
        "description": "苏格兰梗是经典的梗犬品种，以独特的胡须眉毛和威严气质闻名。"
    },
    {
        "breed_id": "097",
        "name_zh": "西藏梗",
        "name_en": "Tibetan Terrier",
        "origin": "中国西藏",
        "size": "中型犬",
        "weight_range": "8-14 kg",
        "height_range": "35-41 cm",
        "lifespan": "12-15年",
        "personality": ["温和友善", "聪明忠诚", "活泼亲人"],
        "coat_color": ["各色均有"],
        "coat_length": "长毛双层",
        "shedding": "低",
        "exercise_need": "中等",
        "feeding_tips": "每日2次",
        "forbidden_foods": ["巧克力", "葡萄"],
        "recommended_food": "中型犬粮",
        "common_diseases": ["髋关节发育不良", "进行性视网膜萎缩", "白内障"],
        "vaccine_schedule": "标准接种程序",
        "grooming": "每日梳毛，防止打结",
        "tags": ["中型犬", "西藏品种", "长毛"],
        "image_url": "",
        "description": "西藏梗其实并非梗犬，而是西藏僧侣培育的伴侣犬，被视为幸运之犬。"
    },
    {
        "breed_id": "098",
        "name_zh": "丝毛梗",
        "name_en": "Silky Terrier",
        "origin": "澳大利亚",
        "size": "小型犬",
        "weight_range": "3-5 kg",
        "height_range": "22-26 cm",
        "lifespan": "12-15年",
        "personality": ["活泼机敏", "自信勇敢", "好奇聪明"],
        "coat_color": ["蓝棕"],
        "coat_length": "长丝滑",
        "shedding": "极低",
        "exercise_need": "中等",
        "feeding_tips": "每日2次",
        "forbidden_foods": ["巧克力"],
        "recommended_food": "小型犬粮",
        "common_diseases": ["髌骨脱位", "气管塌陷", "糖尿病"],
        "vaccine_schedule": "标准接种程序",
        "grooming": "每日梳毛，定期修剪",
        "tags": ["小型犬", "梗犬", "丝滑"],
        "image_url": "",
        "description": "丝毛梗拥有如丝般顺滑的被毛，体型小巧但性格大胆。"
    },
    {
        "breed_id": "099",
        "name_zh": "软毛麦色梗",
        "name_en": "Soft Coated Wheaten Terrier",
        "origin": "爱尔兰",
        "size": "中型犬",
        "weight_range": "14-18 kg",
        "height_range": "43-48 cm",
        "lifespan": "12-14年",
        "personality": ["活泼开朗", "友善温和", "聪明热情"],
        "coat_color": ["麦色"],
        "coat_length": "长丝滑软毛",
        "shedding": "极低",
        "exercise_need": "中高",
        "feeding_tips": "每日2次",
        "forbidden_foods": ["巧克力"],
        "recommended_food": "中型犬粮",
        "common_diseases": ["蛋白丢失性肠病", "肾病", "过敏"],
        "vaccine_schedule": "标准接种程序",
        "grooming": "每日梳毛，定期修剪",
        "tags": ["中型犬", "梗犬", "低敏"],
        "image_url": "",
        "description": "软毛麦色梗以麦穗般金色丝滑被毛和永远快乐的表情著称。"
    },
    {
        "breed_id": "100",
        "name_zh": "拉萨犬",
        "name_en": "Lhasa Apso",
        "origin": "中国西藏",
        "size": "小型犬",
        "weight_range": "5-8 kg",
        "height_range": "25-28 cm",
        "lifespan": "12-15年",
        "personality": ["独立自信", "忠诚警觉", "聪明冷静"],
        "coat_color": ["金色", "白色", "黑色", "各色"],
        "coat_length": "长直毛",
        "shedding": "低",
        "exercise_need": "低",
        "feeding_tips": "每日2次",
        "forbidden_foods": ["巧克力", "葡萄"],
        "recommended_food": "小型犬粮",
        "common_diseases": ["进行性视网膜萎缩", "皮脂腺炎", "髋关节发育不良"],
        "vaccine_schedule": "标准接种程序",
        "grooming": "每日梳毛，定期修剪",
        "tags": ["小型犬", "西藏品种", "守门犬"],
        "image_url": "",
        "description": "拉萨犬原产于西藏，曾作为寺庙守卫犬，以长及地的华丽被毛闻名。"
    },
    {
        "breed_id": "101",
        "name_zh": "平毛寻回犬",
        "name_en": "Flat-Coated Retriever",
        "origin": "英国",
        "size": "大型犬",
        "weight_range": "25-36 kg",
        "height_range": "56-61 cm",
        "lifespan": "8-14年",
        "personality": ["活泼开朗", "友善热情", "永远乐观"],
        "coat_color": ["黑色", "肝色"],
        "coat_length": "中长光滑",
        "shedding": "中高",
        "exercise_need": "高",
        "feeding_tips": "每日2次，高蛋白粮",
        "forbidden_foods": ["巧克力"],
        "recommended_food": "大型运动犬粮",
        "common_diseases": ["恶性肿瘤", "髋关节发育不良", "心脏病"],
        "vaccine_schedule": "标准接种程序",
        "grooming": "每周梳毛2-3次",
        "tags": ["大型犬", "寻回犬", "快乐"],
        "image_url": "",
        "description": "平毛寻回犬被称为\"""犬界的彼得潘\"""，因始终保持幼犬般的快乐和热情。"
    },
    {
        "breed_id": "102",
        "name_zh": "卷毛寻回犬",
        "name_en": "Curly-Coated Retriever",
        "origin": "英国",
        "size": "大型犬",
        "weight_range": "25-40 kg",
        "height_range": "58-69 cm",
        "lifespan": "9-14年",
        "personality": ["独立自信", "聪明敏锐", "忠诚可靠"],
        "coat_color": ["黑色", "肝色"],
        "coat_length": "紧密小卷毛",
        "shedding": "低",
        "exercise_need": "高",
        "feeding_tips": "每日2次",
        "forbidden_foods": ["巧克力"],
        "recommended_food": "大型犬高蛋白粮",
        "common_diseases": ["髋关节发育不良", "胃扭转", "进行性视网膜萎缩"],
        "vaccine_schedule": "标准接种程序",
        "grooming": "不需梳毛，定期修剪",
        "tags": ["大型犬", "寻回犬", "卷毛"],
        "image_url": "",
        "description": "卷毛寻回犬是被毛最独特的寻回犬，紧密的小卷毛具有天然的防水功能。"
    },
    {
        "breed_id": "103",
        "name_zh": "切萨皮克湾寻回犬",
        "name_en": "Chesapeake Bay Retriever",
        "origin": "美国",
        "size": "大型犬",
        "weight_range": "25-36 kg",
        "height_range": "53-66 cm",
        "lifespan": "10-13年",
        "personality": ["忠诚勇敢", "坚毅冷静", "水中能手"],
        "coat_color": ["棕色", "枯草色"],
        "coat_length": "短卷波浪",
        "shedding": "中等",
        "exercise_need": "高",
        "feeding_tips": "每日2次",
        "forbidden_foods": ["巧克力"],
        "recommended_food": "大型犬高能量粮",
        "common_diseases": ["髋关节发育不良", "进行性视网膜萎缩"],
        "vaccine_schedule": "标准接种程序",
        "grooming": "每周梳毛1-2次",
        "tags": ["大型犬", "寻回犬", "水犬"],
        "image_url": "",
        "description": "切萨皮克湾寻回犬拥有防水的波浪状被毛，是美国最耐寒的水上寻回犬。"
    },
    {
        "breed_id": "104",
        "name_zh": "德国短毛指示犬",
        "name_en": "German Shorthaired Pointer",
        "origin": "德国",
        "size": "大型犬",
        "weight_range": "20-32 kg",
        "height_range": "53-64 cm",
        "lifespan": "12-14年",
        "personality": ["活泼热情", "聪明好学", "多才多艺"],
        "coat_color": ["肝色", "肝白花", "黑白"],
        "coat_length": "短毛",
        "shedding": "中等",
        "exercise_need": "极高",
        "feeding_tips": "每日2次高能量粮",
        "forbidden_foods": ["巧克力"],
        "recommended_food": "运动犬高蛋白粮",
        "common_diseases": ["髋关节发育不良", "胃扭转", "癫痫"],
        "vaccine_schedule": "标准接种程序",
        "grooming": "每周梳毛1-2次",
        "tags": ["大型犬", "猎犬", "全能"],
        "image_url": "",
        "description": "德国短毛指示犬是最全能的猎犬之一，陆地水上均表现出色。"
    },
    {
        "breed_id": "105",
        "name_zh": "匈牙利维兹拉犬",
        "name_en": "Vizsla",
        "origin": "匈牙利",
        "size": "中型犬",
        "weight_range": "18-29 kg",
        "height_range": "51-64 cm",
        "lifespan": "12-15年",
        "personality": ["温柔黏人", "活泼好学", "忠诚可靠"],
        "coat_color": ["金锈色"],
        "coat_length": "短毛",
        "shedding": "低",
        "exercise_need": "极高",
        "feeding_tips": "每日2次高能量粮",
        "forbidden_foods": ["巧克力"],
        "recommended_food": "运动犬粮",
        "common_diseases": ["髋关节发育不良", "癫痫", "过敏"],
        "vaccine_schedule": "标准接种程序",
        "grooming": "每周梳毛1次",
        "tags": ["中型犬", "猎犬", "黏人"],
        "image_url": "",
        "description": "匈牙利维兹拉犬被称为\"""魔术贴犬\"""，因其极其黏人的性格得名。"
    },
    {
        "breed_id": "106",
        "name_zh": "英国雪达犬",
        "name_en": "English Setter",
        "origin": "英国",
        "size": "大型犬",
        "weight_range": "20-36 kg",
        "height_range": "61-69 cm",
        "lifespan": "10-12年",
        "personality": ["温柔友善", "活泼亲人", "优雅安静"],
        "coat_color": ["白底斑点", "橙色斑点", "黑斑"],
        "coat_length": "中长丝滑",
        "shedding": "中等",
        "exercise_need": "高",
        "feeding_tips": "每日2次",
        "forbidden_foods": ["巧克力"],
        "recommended_food": "大型运动犬粮",
        "common_diseases": ["髋关节发育不良", "耳聋", "甲状腺功能减退"],
        "vaccine_schedule": "标准接种程序",
        "grooming": "每周梳毛3-4次",
        "tags": ["大型犬", "猎犬", "优雅"],
        "image_url": "",
        "description": "英国雪达犬以其斑点图案和优雅的\"""蹲伏\"""指示动作闻名于世。"
    },
    {
        "breed_id": "107",
        "name_zh": "戈登雪达犬",
        "name_en": "Gordon Setter",
        "origin": "英国苏格兰",
        "size": "大型犬",
        "weight_range": "20-36 kg",
        "height_range": "58-69 cm",
        "lifespan": "10-12年",
        "personality": ["忠诚可靠", "聪明冷静", "勇敢自信"],
        "coat_color": ["黑棕"],
        "coat_length": "中长丝滑",
        "shedding": "中等",
        "exercise_need": "高",
        "feeding_tips": "每日2次",
        "forbidden_foods": ["巧克力"],
        "recommended_food": "大型犬粮",
        "common_diseases": ["髋关节发育不良", "胃扭转", "进行性视网膜萎缩"],
        "vaccine_schedule": "标准接种程序",
        "grooming": "每周梳毛3-4次",
        "tags": ["大型犬", "猎犬", "苏格兰"],
        "image_url": "",
        "description": "戈登雪达犬是雪达犬中最重的品种，以黑棕配色和忠诚可靠的性格闻名。"
    },
    {
        "breed_id": "108",
        "name_zh": "克伦伯猎鹬犬",
        "name_en": "Clumber Spaniel",
        "origin": "英国",
        "size": "中型犬",
        "weight_range": "25-39 kg",
        "height_range": "41-51 cm",
        "lifespan": "10-12年",
        "personality": ["温和安静", "忠诚可靠", "独立冷静"],
        "coat_color": ["白色带橙色或柠檬斑"],
        "coat_length": "中长直毛",
        "shedding": "高",
        "exercise_need": "中等",
        "feeding_tips": "每日2次，控制体重",
        "forbidden_foods": ["巧克力"],
        "recommended_food": "中型犬粮",
        "common_diseases": ["眼疾", "髋关节发育不良", "耳部感染"],
        "vaccine_schedule": "标准接种程序",
        "grooming": "每周梳毛3-4次，定期清洁耳朵",
        "tags": ["中型犬", "猎犬", "稳重"],
        "image_url": "",
        "description": "克伦伯猎鹬犬是猎鹬犬家族中最稳重的品种，以低沉的身体和温和的性格著称。"
    },
    {
        "breed_id": "109",
        "name_zh": "英国激飞猎犬",
        "name_en": "English Springer Spaniel",
        "origin": "英国",
        "size": "中型犬",
        "weight_range": "18-25 kg",
        "height_range": "46-51 cm",
        "lifespan": "12-14年",
        "personality": ["活泼开朗", "友善亲人", "工作热情"],
        "coat_color": ["肝白", "黑白"],
        "coat_length": "中长毛",
        "shedding": "中等",
        "exercise_need": "高",
        "feeding_tips": "每日2次",
        "forbidden_foods": ["巧克力"],
        "recommended_food": "中型运动犬粮",
        "common_diseases": ["髋关节发育不良", "进行性视网膜萎缩", "耳部感染"],
        "vaccine_schedule": "标准接种程序",
        "grooming": "每周梳毛3-4次，定期修剪",
        "tags": ["中型犬", "猎犬", "家庭犬"],
        "image_url": "",
        "description": "英国激飞猎犬是猎犬中最受欢迎的家庭伴侣之一，既能狩猎也能陪伴。"
    },
    {
        "breed_id": "110",
        "name_zh": "萨塞克斯猎犬",
        "name_en": "Sussex Spaniel",
        "origin": "英国",
        "size": "中型犬",
        "weight_range": "16-20 kg",
        "height_range": "33-38 cm",
        "lifespan": "11-13年",
        "personality": ["温和友善", "忠诚稳重", "开朗亲人"],
        "coat_color": ["金肝色"],
        "coat_length": "中长波浪",
        "shedding": "中等",
        "exercise_need": "中等",
        "feeding_tips": "每日2次",
        "forbidden_foods": ["巧克力"],
        "recommended_food": "中型犬粮",
        "common_diseases": ["髋关节发育不良", "耳部感染", "心脏病"],
        "vaccine_schedule": "标准接种程序",
        "grooming": "每周梳毛3-4次",
        "tags": ["中型犬", "猎犬", "稀有"],
        "image_url": "",
        "description": "萨塞克斯猎犬以独特的金肝色被毛和喜欢出声\"""说话\"""的习惯闻名。"
    },
    {
        "breed_id": "111",
        "name_zh": "爱尔兰水猎犬",
        "name_en": "Irish Water Spaniel",
        "origin": "爱尔兰",
        "size": "大型犬",
        "weight_range": "20-30 kg",
        "height_range": "53-61 cm",
        "lifespan": "10-12年",
        "personality": ["活泼聪明", "勇敢自信", "顽皮热情"],
        "coat_color": ["肝色"],
        "coat_length": "紧密卷毛",
        "shedding": "极低",
        "exercise_need": "高",
        "feeding_tips": "每日2次",
        "forbidden_foods": ["巧克力"],
        "recommended_food": "大型运动犬粮",
        "common_diseases": ["髋关节发育不良", "甲状腺功能减退"],
        "vaccine_schedule": "标准接种程序",
        "grooming": "每周梳毛2-3次",
        "tags": ["大型犬", "猎犬", "水犬"],
        "image_url": "",
        "description": "爱尔兰水猎犬以独特的\"""老鼠尾巴\"""和全身紧密卷毛为特征。"
    },
    {
        "breed_id": "112",
        "name_zh": "库瓦兹犬",
        "name_en": "Kuvasz",
        "origin": "匈牙利",
        "size": "大型犬",
        "weight_range": "30-52 kg",
        "height_range": "66-76 cm",
        "lifespan": "10-12年",
        "personality": ["忠诚护主", "独立勇敢", "冷静沉稳"],
        "coat_color": ["纯白"],
        "coat_length": "中长波浪",
        "shedding": "高",
        "exercise_need": "高",
        "feeding_tips": "每日2次大型犬粮",
        "forbidden_foods": ["巧克力", "高盐食物"],
        "recommended_food": "大型护卫犬粮",
        "common_diseases": ["髋关节发育不良", "胃扭转", "甲状腺功能减退"],
        "vaccine_schedule": "标准接种程序",
        "grooming": "每周梳毛3-4次",
        "tags": ["大型犬", "护卫犬", "白犬"],
        "image_url": "",
        "description": "库瓦兹犬是匈牙利古老的皇室护卫犬，纯白被毛使其在羊群中不显眼。"
    },
    {
        "breed_id": "113",
        "name_zh": "史奇派克犬",
        "name_en": "Schipperke",
        "origin": "比利时",
        "size": "小型犬",
        "weight_range": "3-9 kg",
        "height_range": "25-33 cm",
        "lifespan": "12-16年",
        "personality": ["活泼好奇", "机警忠诚", "勇敢自信"],
        "coat_color": ["纯黑"],
        "coat_length": "中等双层",
        "shedding": "中高",
        "exercise_need": "中高",
        "feeding_tips": "每日2次",
        "forbidden_foods": ["巧克力"],
        "recommended_food": "小型犬高能量粮",
        "common_diseases": ["髌骨脱位", "黏多糖贮积症", "甲状腺功能减退"],
        "vaccine_schedule": "标准接种程序",
        "grooming": "每周梳毛2-3次",
        "tags": ["小型犬", "看门犬", "黑色"],
        "image_url": "",
        "description": "史奇派克犬被称为\"""小船长\"""，因在比利时运河船上捕鼠和守卫而得名。"
    },
    {
        "breed_id": "114",
        "name_zh": "格罗安达犬",
        "name_en": "Groenendael",
        "origin": "比利时",
        "size": "大型犬",
        "weight_range": "20-30 kg",
        "height_range": "56-66 cm",
        "lifespan": "12-14年",
        "personality": ["聪明敏锐", "忠诚勇敢", "工作热情"],
        "coat_color": ["纯黑"],
        "coat_length": "长毛",
        "shedding": "高",
        "exercise_need": "极高",
        "feeding_tips": "每日2次高蛋白粮",
        "forbidden_foods": ["巧克力"],
        "recommended_food": "大型工作犬粮",
        "common_diseases": ["髋关节发育不良", "癫痫", "甲状腺功能减退"],
        "vaccine_schedule": "标准接种程序",
        "grooming": "每周梳毛3-5次，换毛季每天",
        "tags": ["大型犬", "牧羊犬", "警犬"],
        "image_url": "",
        "description": "格罗安达犬是比利时牧羊犬的四个变种之一，以纯黑长毛和极高的智商闻名。"
    },
    {
        "breed_id": "115",
        "name_zh": "伯瑞犬",
        "name_en": "Briard",
        "origin": "法国",
        "size": "大型犬",
        "weight_range": "25-41 kg",
        "height_range": "56-69 cm",
        "lifespan": "10-12年",
        "personality": ["忠诚保护", "聪明独立", "勇敢温柔"],
        "coat_color": ["黑色", "黄褐色", "灰色"],
        "coat_length": "长山羊毛",
        "shedding": "极低",
        "exercise_need": "高",
        "feeding_tips": "每日2次",
        "forbidden_foods": ["巧克力"],
        "recommended_food": "大型犬粮",
        "common_diseases": ["髋关节发育不良", "胃扭转", "夜盲症"],
        "vaccine_schedule": "标准接种程序",
        "grooming": "每周梳毛4-5次",
        "tags": ["大型犬", "牧羊犬", "法国"],
        "image_url": "",
        "description": "伯瑞犬以独特的山羊般长毛和脚后跟双悬爪为特征，是法国古老的牧羊犬。"
    },
    {
        "breed_id": "116",
        "name_zh": "澳大利亚凯尔皮犬",
        "name_en": "Australian Kelpie",
        "origin": "澳大利亚",
        "size": "中型犬",
        "weight_range": "11-21 kg",
        "height_range": "43-51 cm",
        "lifespan": "12-15年",
        "personality": ["聪明敏捷", "工作狂热", "忠诚独立"],
        "coat_color": ["黑色", "红色", "巧克力色", "蓝色"],
        "coat_length": "短毛",
        "shedding": "中等",
        "exercise_need": "极高",
        "feeding_tips": "每日2次高能量粮",
        "forbidden_foods": ["巧克力"],
        "recommended_food": "运动犬高蛋白粮",
        "common_diseases": ["进行性视网膜萎缩", "髋关节发育不良"],
        "vaccine_schedule": "标准接种程序",
        "grooming": "每周梳毛1-2次",
        "tags": ["中型犬", "牧羊犬", "工作犬"],
        "image_url": "",
        "description": "澳大利亚凯尔皮犬是澳洲最出色的牧羊犬，以惊人的耐力和智力闻名。"
    },
    {
        "breed_id": "117",
        "name_zh": "可蒙犬",
        "name_en": "Komondor",
        "origin": "匈牙利",
        "size": "超大型犬",
        "weight_range": "36-61 kg",
        "height_range": "65-76 cm",
        "lifespan": "10-12年",
        "personality": ["忠诚护主", "独立冷静", "勇敢坚决"],
        "coat_color": ["白色"],
        "coat_length": "绳索状",
        "shedding": "极低",
        "exercise_need": "中等",
        "feeding_tips": "每日2次大型犬粮",
        "forbidden_foods": ["巧克力", "高盐食物"],
        "recommended_food": "超大型护卫犬粮",
        "common_diseases": ["髋关节发育不良", "胃扭转", "眼疾"],
        "vaccine_schedule": "标准接种程序",
        "grooming": "绳索毛需专业护理，不可梳理",
        "tags": ["超大型犬", "护卫犬", "拖把犬"],
        "image_url": "",
        "description": "可蒙犬以独特的拖把式绳索被毛闻名于世，是匈牙利国宝级护卫犬。"
    },
    {
        "breed_id": "118",
        "name_zh": "英国古代牧羊犬",
        "name_en": "Old English Sheepdog",
        "origin": "英国",
        "size": "大型犬",
        "weight_range": "27-45 kg",
        "height_range": "51-61 cm",
        "lifespan": "10-12年",
        "personality": ["温柔友善", "活泼聪明", "亲人忠诚"],
        "coat_color": ["灰白", "蓝灰"],
        "coat_length": "长蓬松毛",
        "shedding": "高",
        "exercise_need": "高",
        "feeding_tips": "每日2次",
        "forbidden_foods": ["巧克力"],
        "recommended_food": "大型犬粮",
        "common_diseases": ["髋关节发育不良", "白内障", "耳聋"],
        "vaccine_schedule": "标准接种程序",
        "grooming": "每日梳毛，每6-8周修剪",
        "tags": ["大型犬", "牧羊犬", "毛茸茸"],
        "image_url": "",
        "description": "英国古代牧羊犬以蓬松可爱的外形和温柔的性格成为最受欢迎的家庭犬之一。"
    },
    {
        "breed_id": "119",
        "name_zh": "法兰德斯牧牛犬",
        "name_en": "Bouvier des Flandres",
        "origin": "比利时",
        "size": "大型犬",
        "weight_range": "27-40 kg",
        "height_range": "59-69 cm",
        "lifespan": "10-12年",
        "personality": ["忠诚可靠", "勇敢冷静", "温和稳重"],
        "coat_color": ["黑色", "灰色", "斑纹"],
        "coat_length": "粗糙刚毛",
        "shedding": "低",
        "exercise_need": "高",
        "feeding_tips": "每日2次",
        "forbidden_foods": ["巧克力"],
        "recommended_food": "大型工作犬粮",
        "common_diseases": ["髋关节发育不良", "胃扭转", "青光眼"],
        "vaccine_schedule": "标准接种程序",
        "grooming": "每周梳毛2-3次，定期修剪",
        "tags": ["大型犬", "牧牛犬", "护卫犬"],
        "image_url": "",
        "description": "法兰德斯牧牛犬是比利时古老的农场犬，胡须和眉毛是其标志性特征。"
    },
    {
        "breed_id": "120",
        "name_zh": "迷你杜宾犬",
        "name_en": "Miniature Pinscher",
        "origin": "德国",
        "size": "小型犬",
        "weight_range": "3-6 kg",
        "height_range": "25-30 cm",
        "lifespan": "12-16年",
        "personality": ["活泼自信", "勇敢好动", "聪明机警"],
        "coat_color": ["红棕色", "黑棕"],
        "coat_length": "短毛",
        "shedding": "低",
        "exercise_need": "中高",
        "feeding_tips": "每日2次",
        "forbidden_foods": ["巧克力"],
        "recommended_food": "小型犬高能量粮",
        "common_diseases": ["髌骨脱位", "心脏病", "进行性视网膜萎缩"],
        "vaccine_schedule": "标准接种程序",
        "grooming": "每周梳毛1次",
        "tags": ["小型犬", "迷你", "活跃"],
        "image_url": "",
        "description": "迷你杜宾犬外形似迷你版杜宾犬，但两者无血缘关系，是自信活泼的小型伴侣犬。"
    },
]

# 为品种列表创建快速索引
BREED_INDEX = {b["breed_id"]: b for b in BREEDS_DATA}
BREED_SEARCH_INDEX = {b["name_zh"]: b for b in BREEDS_DATA}
BREED_SEARCH_INDEX.update({b["name_en"].lower(): b for b in BREEDS_DATA})


def get_breed_by_id(breed_id: str):
    return BREED_INDEX.get(breed_id)


def search_breeds(query: str, page: int = 1, size: int = 20):
    query_lower = query.lower()
    results = [
        b for b in BREEDS_DATA
        if query_lower in b["name_zh"].lower()
        or query_lower in b["name_en"].lower()
        or query_lower in b["origin"].lower()
        or any(query_lower in tag for tag in b["tags"])
    ]
    total = len(results)
    start = (page - 1) * size
    end = start + size
    return results[start:end], total


def get_all_breeds(page: int = 1, size: int = 20):
    total = len(BREEDS_DATA)
    start = (page - 1) * size
    end = start + size
    return BREEDS_DATA[start:end], total


def get_random_breed():
    import random
    return random.choice(BREEDS_DATA)
